//! Two-phase borrowing and reborrowing support.
//!
//! Implements the two-phase borrow pattern where a mutable borrow is
//! initially in a "reserved" state (allowing shared access) and later
//! "activated" on the first mutable use.
//!
//! # Two-Phase Borrows
//!
//! Pattern: `vec.push(vec.len())` — the `&mut self` for `push` is reserved
//! while `len()` takes a shared borrow of `vec`. The mutable borrow is only
//! activated when `push` actually starts writing.
//!
//! # Reborrowing
//!
//! `let r2 = &*r1` creates a new loan with a subset relationship to `r1`'s
//! origin. The original borrow is suspended while the reborrow is active.

use std::collections::HashMap;

use crate::lexer::token::Span;
use crate::parser::ast::*;

use super::facts::{Loan, Mutability, Origin, Place, Point, PointKind, PoloniusFacts};

// ═══════════════════════════════════════════════════════════════════════
// Borrow phase tracking
// ═══════════════════════════════════════════════════════════════════════

/// The phase of a two-phase mutable borrow.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BorrowPhase {
    /// The borrow exists but hasn't been used mutably yet.
    /// Shared access to the borrowed place is still allowed.
    Reserved,
    /// The borrow has been used mutably — exclusive access is enforced.
    Activated,
}

impl std::fmt::Display for BorrowPhase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BorrowPhase::Reserved => write!(f, "reserved"),
            BorrowPhase::Activated => write!(f, "activated"),
        }
    }
}

/// Information about a two-phase borrow.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TwoPhaseBorrow {
    /// The loan that is in two-phase mode.
    pub loan: Loan,
    /// Current phase of the borrow.
    pub phase: BorrowPhase,
    /// The point where the borrow was reserved.
    pub reserved_at: Point,
    /// The point where the borrow was activated (if activated).
    pub activated_at: Option<Point>,
}

/// Information about a reborrow relationship.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Reborrow {
    /// The new loan created by the reborrow.
    pub new_loan: Loan,
    /// The original loan being reborrowed.
    pub original_loan: Loan,
    /// The point where the reborrow occurred.
    pub point: Point,
}

// ═══════════════════════════════════════════════════════════════════════
// TwoPhaseAnalyzer
// ═══════════════════════════════════════════════════════════════════════

/// Analyzes two-phase borrows and reborrowing in a function body.
///
/// Walks the AST to detect two-phase borrow patterns and reborrow chains,
/// then augments the `PoloniusFacts` with appropriate reservation and
/// activation facts plus subset relationships.
pub struct TwoPhaseAnalyzer {
    /// Tracked two-phase borrows.
    two_phase_borrows: Vec<TwoPhaseBorrow>,
    /// Tracked reborrow relationships.
    reborrows: Vec<Reborrow>,
    /// Maps loan IDs to their active borrow info.
    active_loans: HashMap<u32, TwoPhaseBorrow>,
    /// Maps variable names to the loan ID holding a borrow of them.
    var_to_loan: HashMap<String, Vec<u32>>,
    /// Next loan ID for generating new loans.
    next_loan_id: u32,
    /// Next origin ID for generating new origins.
    next_origin_id: u32,
    /// Additional facts to merge.
    extra_facts: PoloniusFacts,
    /// Current program point.
    current_block: u32,
    /// Current statement index.
    current_stmt: u32,
}

impl TwoPhaseAnalyzer {
    /// Creates a new two-phase analyzer.
    ///
    /// `start_loan_id` and `start_origin_id` should be set to the next
    /// available IDs from the main fact generator.
    pub fn new(start_loan_id: u32, start_origin_id: u32) -> Self {
        Self {
            two_phase_borrows: Vec::new(),
            reborrows: Vec::new(),
            active_loans: HashMap::new(),
            var_to_loan: HashMap::new(),
            next_loan_id: start_loan_id,
            next_origin_id: start_origin_id,
            extra_facts: PoloniusFacts::new(),
            current_block: 0,
            current_stmt: 0,
        }
    }

    /// Returns the list of detected two-phase borrows.
    pub fn two_phase_borrows(&self) -> &[TwoPhaseBorrow] {
        &self.two_phase_borrows
    }

    /// Returns the list of detected reborrows.
    pub fn reborrows(&self) -> &[Reborrow] {
        &self.reborrows
    }

    /// Returns additional facts generated by two-phase analysis.
    pub fn extra_facts(&self) -> &PoloniusFacts {
        &self.extra_facts
    }

    /// Analyzes a method call for two-phase borrow pattern.
    ///
    /// Detects patterns like `v.push(v.len())` where the `&mut self`
    /// is reserved during argument evaluation and activated on call.
    pub fn analyze_method_call(
        &mut self,
        receiver_place: &Place,
        _method: &str,
        args: &[Expr],
        is_mutable_method: bool,
        span: Span,
    ) {
        if !is_mutable_method {
            return;
        }

        let reserve_point = self.current_point();

        // Create the reserved mutable loan.
        let loan = self.fresh_loan(receiver_place.clone(), Mutability::Mutable, span);

        let two_phase = TwoPhaseBorrow {
            loan: loan.clone(),
            phase: BorrowPhase::Reserved,
            reserved_at: reserve_point,
            activated_at: None,
        };

        self.active_loans.insert(loan.id, two_phase.clone());
        self.var_to_loan
            .entry(receiver_place.root().to_string())
            .or_default()
            .push(loan.id);
        self.two_phase_borrows.push(two_phase);

        // Check if any args borrow the same place (the two-phase pattern).
        let has_shared_arg = self.args_borrow_place(args, receiver_place);

        if has_shared_arg {
            // Loan stays reserved during argument evaluation.
            // It will be activated after arguments are evaluated.
            let activate_point = Point {
                block: self.current_block,
                statement: self.current_stmt + 1,
                kind: PointKind::Start,
            };
            self.activate_loan(loan.id, activate_point);
        } else {
            // Activate immediately.
            self.activate_loan(loan.id, reserve_point);
        }
    }

    /// Records a reborrow: `let r2 = &*r1` or `let r2 = &mut *r1`.
    pub fn record_reborrow(
        &mut self,
        new_place: &Place,
        original_place: &Place,
        mutability: Mutability,
        span: Span,
    ) {
        let point = self.current_point();
        let new_origin = self.fresh_origin();
        let new_loan = self.fresh_loan(new_place.clone(), mutability, span);

        // Find the original loan on the original place.
        let original_loan_id = self
            .var_to_loan
            .get(original_place.root())
            .and_then(|ids| ids.last().copied());

        if let Some(orig_id) = original_loan_id {
            if let Some(orig_two_phase) = self.active_loans.get(&orig_id) {
                let orig_loan = orig_two_phase.loan.clone();

                // Subset: new_origin ⊆ original_origin.
                // The new borrow's region is contained within the original's.
                let orig_origin = Origin(orig_id);
                self.extra_facts
                    .subset
                    .push((new_origin, orig_origin, point));

                self.reborrows.push(Reborrow {
                    new_loan: new_loan.clone(),
                    original_loan: orig_loan,
                    point,
                });
            }
        }

        // Issue the new loan.
        self.extra_facts
            .loan_issued_at
            .push((new_origin, new_loan.clone(), point));

        self.var_to_loan
            .entry(new_place.root().to_string())
            .or_default()
            .push(new_loan.id);
    }

    /// Analyzes a borrow expression for nested field-level tracking.
    ///
    /// `&self.field` borrows the struct at field granularity, allowing
    /// simultaneous borrows of different fields.
    pub fn analyze_field_borrow(&mut self, place: &Place, mutability: Mutability, span: Span) {
        let point = self.current_point();
        let origin = self.fresh_origin();
        let loan = self.fresh_loan(place.clone(), mutability, span);

        self.extra_facts
            .loan_issued_at
            .push((origin, loan.clone(), point));

        self.var_to_loan
            .entry(place.root().to_string())
            .or_default()
            .push(loan.id);
    }

    /// Sets the current program position.
    pub fn set_position(&mut self, block: u32, stmt: u32) {
        self.current_block = block;
        self.current_stmt = stmt;
    }

    /// Merges extra facts into the main fact set.
    pub fn merge_into(&self, facts: &mut PoloniusFacts) {
        facts
            .loan_issued_at
            .extend(self.extra_facts.loan_issued_at.iter().cloned());
        facts.origin_contains_loan_on_entry.extend(
            self.extra_facts
                .origin_contains_loan_on_entry
                .iter()
                .cloned(),
        );
        facts.subset.extend(self.extra_facts.subset.iter().copied());
        facts
            .loan_invalidated_at
            .extend(self.extra_facts.loan_invalidated_at.iter().cloned());
        facts
            .loan_killed_at
            .extend(self.extra_facts.loan_killed_at.iter().cloned());
    }
}

// ── Private helpers ────────────────────────────────────────────────────

impl TwoPhaseAnalyzer {
    fn current_point(&self) -> Point {
        Point {
            block: self.current_block,
            statement: self.current_stmt,
            kind: PointKind::Start,
        }
    }

    fn fresh_loan(&mut self, place: Place, mutability: Mutability, span: Span) -> Loan {
        let loan = Loan {
            id: self.next_loan_id,
            place,
            mutability,
            span,
        };
        self.next_loan_id += 1;
        loan
    }

    fn fresh_origin(&mut self) -> Origin {
        let o = Origin(self.next_origin_id);
        self.next_origin_id += 1;
        o
    }

    fn activate_loan(&mut self, loan_id: u32, point: Point) {
        if let Some(two_phase) = self.active_loans.get_mut(&loan_id) {
            two_phase.phase = BorrowPhase::Activated;
            two_phase.activated_at = Some(point);
        }
        // Update in the two_phase_borrows list too.
        for tp in &mut self.two_phase_borrows {
            if tp.loan.id == loan_id {
                tp.phase = BorrowPhase::Activated;
                tp.activated_at = Some(point);
            }
        }
    }

    /// Checks if any argument expressions borrow the given place.
    fn args_borrow_place(&self, args: &[Expr], place: &Place) -> bool {
        args.iter().any(|arg| expr_borrows_place(arg, place))
    }
}

/// Recursively checks if an expression borrows the given place.
fn expr_borrows_place(expr: &Expr, place: &Place) -> bool {
    match expr {
        Expr::Unary {
            op: UnaryOp::Ref | UnaryOp::RefMut,
            operand,
            ..
        } => expr_is_place(operand, place),
        Expr::MethodCall { receiver, .. } => expr_is_place(receiver, place),
        Expr::Call { args, .. } => args.iter().any(|a| expr_borrows_place(&a.value, place)),
        Expr::Binary { left, right, .. } => {
            expr_borrows_place(left, place) || expr_borrows_place(right, place)
        }
        _ => false,
    }
}

/// Checks if an expression refers to the given place.
fn expr_is_place(expr: &Expr, place: &Place) -> bool {
    match expr {
        Expr::Ident { name, .. } => name == place.root(),
        Expr::Field { object, field, .. } => {
            if let Some(proj) = place.projections.first() {
                if let super::facts::PlaceProjection::Field(f) = proj {
                    f == field && expr_is_place(object, &Place::from_var(place.root()))
                } else {
                    false
                }
            } else {
                expr_is_place(object, place)
            }
        }
        _ => false,
    }
}

impl Default for TwoPhaseAnalyzer {
    fn default() -> Self {
        Self::new(0, 0)
    }
}

// ═══════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analyzer::polonius::facts::{Mutability, Place, PlaceProjection};
    use crate::lexer::token::Span;

    fn span(s: usize, e: usize) -> Span {
        Span::new(s, e)
    }

    fn ident_expr(name: &str, s: usize, e: usize) -> Expr {
        Expr::Ident {
            name: name.to_string(),
            span: span(s, e),
        }
    }

    fn int_lit(val: i64, s: usize, e: usize) -> Expr {
        Expr::Literal {
            kind: LiteralKind::Int(val),
            span: span(s, e),
        }
    }

    fn method_call_expr(receiver: Expr, method: &str, args: Vec<Expr>, s: usize, e: usize) -> Expr {
        Expr::MethodCall {
            receiver: Box::new(receiver),
            method: method.to_string(),
            args: args
                .into_iter()
                .map(|a| {
                    let arg_span = match &a {
                        Expr::Literal { span, .. }
                        | Expr::Ident { span, .. }
                        | Expr::MethodCall { span, .. }
                        | Expr::Call { span, .. } => *span,
                        _ => span(s, e),
                    };
                    CallArg {
                        name: None,
                        value: a,
                        span: arg_span,
                    }
                })
                .collect(),
            span: span(s, e),
        }
    }

    // ── S11.1: Two-phase borrow detection ─────────────────────────────

    #[test]
    fn s11_1_two_phase_borrow_detected() {
        let mut analyzer = TwoPhaseAnalyzer::new(0, 0);
        let place = Place::from_var("vec");

        // vec.push(vec.len()) — &mut self for push, shared borrow for len()
        let args = vec![method_call_expr(
            ident_expr("vec", 10, 13),
            "len",
            vec![],
            10,
            19,
        )];

        analyzer.analyze_method_call(&place, "push", &args, true, span(0, 20));

        assert_eq!(analyzer.two_phase_borrows().len(), 1);
        let tp = &analyzer.two_phase_borrows()[0];
        assert_eq!(tp.loan.place.base, "vec");
        assert_eq!(tp.loan.mutability, Mutability::Mutable);
    }

    // ── S11.2: Reserved phase allows shared access ────────────────────

    #[test]
    fn s11_2_reserved_phase_exists_before_activation() {
        let mut analyzer = TwoPhaseAnalyzer::new(0, 0);
        let place = Place::from_var("v");

        // v.push(v.len()) — two-phase: reserved during len(), activated after
        let args = vec![method_call_expr(
            ident_expr("v", 8, 9),
            "len",
            vec![],
            8,
            14,
        )];

        analyzer.analyze_method_call(&place, "push", &args, true, span(0, 15));

        // The borrow should have been activated (since analysis completes).
        let tp = &analyzer.two_phase_borrows()[0];
        assert!(
            tp.activated_at.is_some(),
            "two-phase borrow should be activated after analysis"
        );
        assert_ne!(
            tp.reserved_at,
            tp.activated_at.expect("should have activation point"),
            "reservation and activation should be at different points"
        );
    }

    // ── S11.3: Immediate activation for non-two-phase ─────────────────

    #[test]
    fn s11_3_immediate_activation_no_shared_arg() {
        let mut analyzer = TwoPhaseAnalyzer::new(0, 0);
        let place = Place::from_var("v");

        // v.push(42) — no shared borrow of v in args
        let args = vec![int_lit(42, 8, 10)];

        analyzer.analyze_method_call(&place, "push", &args, true, span(0, 11));

        let tp = &analyzer.two_phase_borrows()[0];
        assert_eq!(
            tp.reserved_at,
            tp.activated_at.expect("should be activated"),
            "without two-phase pattern, borrow activates immediately"
        );
    }

    // ── S11.4: Reborrow creates subset relationship ───────────────────

    #[test]
    fn s11_4_reborrow_creates_subset() {
        let mut analyzer = TwoPhaseAnalyzer::new(0, 0);
        let original = Place::from_var("r1");
        let new_place = Place::from_var("r2");

        // First, simulate an existing loan on r1.
        let loan = Loan {
            id: 0,
            place: original.clone(),
            mutability: Mutability::Mutable,
            span: span(0, 5),
        };
        let two_phase = TwoPhaseBorrow {
            loan,
            phase: BorrowPhase::Activated,
            reserved_at: Point {
                block: 0,
                statement: 0,
                kind: PointKind::Start,
            },
            activated_at: Some(Point {
                block: 0,
                statement: 0,
                kind: PointKind::Start,
            }),
        };
        analyzer.active_loans.insert(0, two_phase);
        analyzer
            .var_to_loan
            .entry("r1".to_string())
            .or_default()
            .push(0);
        analyzer.next_loan_id = 1;
        analyzer.next_origin_id = 1;

        // let r2 = &*r1
        analyzer.record_reborrow(&new_place, &original, Mutability::Shared, span(10, 15));

        assert_eq!(analyzer.reborrows().len(), 1);
        let rb = &analyzer.reborrows()[0];
        assert_eq!(rb.original_loan.id, 0);
        assert_eq!(rb.new_loan.place.base, "r2");

        // Should have subset facts.
        assert!(
            !analyzer.extra_facts().subset.is_empty(),
            "reborrow should create subset relationship"
        );
    }

    // ── S11.5: Mutable reborrow tracked ───────────────────────────────

    #[test]
    fn s11_5_mutable_reborrow_tracked() {
        let mut analyzer = TwoPhaseAnalyzer::new(0, 0);
        let original = Place::from_var("r1");
        let new_place = Place::from_var("r2");

        // Setup existing loan.
        let loan = Loan {
            id: 0,
            place: original.clone(),
            mutability: Mutability::Mutable,
            span: span(0, 5),
        };
        analyzer.active_loans.insert(
            0,
            TwoPhaseBorrow {
                loan,
                phase: BorrowPhase::Activated,
                reserved_at: Point {
                    block: 0,
                    statement: 0,
                    kind: PointKind::Start,
                },
                activated_at: Some(Point {
                    block: 0,
                    statement: 0,
                    kind: PointKind::Start,
                }),
            },
        );
        analyzer
            .var_to_loan
            .entry("r1".to_string())
            .or_default()
            .push(0);
        analyzer.next_loan_id = 1;
        analyzer.next_origin_id = 1;

        // let r2 = &mut *r1
        analyzer.record_reborrow(&new_place, &original, Mutability::Mutable, span(10, 20));

        assert_eq!(analyzer.reborrows().len(), 1);
        assert_eq!(
            analyzer.reborrows()[0].new_loan.mutability,
            Mutability::Mutable
        );
    }

    // ── S11.6: Field-level borrow granularity ─────────────────────────

    #[test]
    fn s11_6_field_borrow_granularity() {
        let mut analyzer = TwoPhaseAnalyzer::new(0, 0);

        // &self.x — borrows at field granularity
        let place = Place::from_var("self").with_field("x");
        analyzer.analyze_field_borrow(&place, Mutability::Shared, span(0, 10));

        let issued = &analyzer.extra_facts().loan_issued_at;
        assert_eq!(issued.len(), 1);
        let (_, loan, _) = &issued[0];
        assert_eq!(loan.place.base, "self");
        assert_eq!(
            loan.place.projections,
            vec![PlaceProjection::Field("x".to_string())]
        );
    }

    // ── S11.7: Different fields can be borrowed simultaneously ────────

    #[test]
    fn s11_7_different_fields_simultaneous() {
        let mut analyzer = TwoPhaseAnalyzer::new(0, 0);

        let place_x = Place::from_var("s").with_field("x");
        let place_y = Place::from_var("s").with_field("y");

        analyzer.analyze_field_borrow(&place_x, Mutability::Mutable, span(0, 10));
        analyzer.analyze_field_borrow(&place_y, Mutability::Mutable, span(12, 22));

        // Two field loans on different fields should both be issued.
        assert_eq!(analyzer.extra_facts().loan_issued_at.len(), 2);

        let loan0 = &analyzer.extra_facts().loan_issued_at[0].1;
        let loan1 = &analyzer.extra_facts().loan_issued_at[1].1;

        assert_ne!(
            loan0.place, loan1.place,
            "loans should be on different fields"
        );
    }

    // ── S11.8: Merge into main facts ──────────────────────────────────

    #[test]
    fn s11_8_merge_into_main_facts() {
        let mut analyzer = TwoPhaseAnalyzer::new(0, 0);
        let place = Place::from_var("s").with_field("x");
        analyzer.analyze_field_borrow(&place, Mutability::Shared, span(0, 10));

        let mut main_facts = PoloniusFacts::new();
        assert!(main_facts.loan_issued_at.is_empty());

        analyzer.merge_into(&mut main_facts);
        assert_eq!(main_facts.loan_issued_at.len(), 1);
    }

    // ── S11.9: Non-mutable method call not tracked ────────────────────

    #[test]
    fn s11_9_shared_method_not_two_phase() {
        let mut analyzer = TwoPhaseAnalyzer::new(0, 0);
        let place = Place::from_var("v");

        // v.len() — shared method, no two-phase needed
        analyzer.analyze_method_call(&place, "len", &[], false, span(0, 8));

        assert!(
            analyzer.two_phase_borrows().is_empty(),
            "shared methods should not create two-phase borrows"
        );
    }

    // ── S11.10: Position tracking ─────────────────────────────────────

    #[test]
    fn s11_10_position_tracking() {
        let mut analyzer = TwoPhaseAnalyzer::new(0, 0);
        analyzer.set_position(3, 7);

        let place = Place::from_var("x");
        analyzer.analyze_field_borrow(&place, Mutability::Shared, span(0, 5));

        let (_, _, point) = &analyzer.extra_facts().loan_issued_at[0];
        assert_eq!(point.block, 3);
        assert_eq!(point.statement, 7);
    }
}
