//! Linker script generation for bare-metal targets.
//!
//! Generates GNU ld-compatible linker scripts with proper ELF sections
//! for text, data, bss, and stack layout.

use super::target::{Arch, TargetConfig};
use super::CodegenError;

/// Memory region definition for linker scripts.
#[derive(Debug, Clone)]
pub struct MemoryRegion {
    /// Region name (e.g., "FLASH", "RAM").
    pub name: String,
    /// Base address.
    pub origin: u64,
    /// Size in bytes.
    pub size: u64,
    /// Attributes: r=read, w=write, x=execute.
    pub attrs: String,
}

/// Linker script configuration.
#[derive(Debug, Clone)]
pub struct LinkerConfig {
    /// Memory regions.
    pub regions: Vec<MemoryRegion>,
    /// Stack size in bytes.
    pub stack_size: u64,
    /// Entry point symbol.
    pub entry: String,
}

impl LinkerConfig {
    /// Creates a default linker config for the given target.
    pub fn for_target(target: &TargetConfig) -> Self {
        match target.arch {
            Arch::Aarch64 => Self {
                regions: vec![
                    MemoryRegion {
                        name: "FLASH".into(),
                        origin: 0x4000_0000,
                        size: 16 * 1024 * 1024, // 16MB kernel .text
                        attrs: "rx".into(),
                    },
                    MemoryRegion {
                        name: "RAM".into(),
                        origin: 0x4100_0000,
                        size: 128 * 1024 * 1024, // 128MB kernel data+heap+stack
                        attrs: "rwx".into(),
                    },
                ],
                stack_size: 64 * 1024, // 64KB kernel stack
                entry: "_start".into(),
            },
            Arch::Riscv64 => Self {
                regions: vec![
                    MemoryRegion {
                        name: "FLASH".into(),
                        origin: 0x2000_0000,
                        size: 16 * 1024 * 1024, // 16MB
                        attrs: "rx".into(),
                    },
                    MemoryRegion {
                        name: "RAM".into(),
                        origin: 0x8000_0000,
                        size: 64 * 1024 * 1024, // 64MB
                        attrs: "rwx".into(),
                    },
                ],
                stack_size: 8192,
                entry: "_start".into(),
            },
            Arch::X86_64 => Self {
                regions: vec![
                    MemoryRegion {
                        name: "FLASH".into(),
                        origin: 0x0010_0000, // 1MB
                        size: 16 * 1024 * 1024,
                        attrs: "rx".into(),
                    },
                    MemoryRegion {
                        name: "RAM".into(),
                        origin: 0x0200_0000,
                        size: 64 * 1024 * 1024,
                        attrs: "rwx".into(),
                    },
                ],
                stack_size: 16384,
                entry: "_start".into(),
            },
        }
    }

    /// Sets the stack size.
    pub fn with_stack_size(mut self, size: u64) -> Self {
        self.stack_size = size;
        self
    }

    /// Sets the entry point.
    pub fn with_entry(mut self, entry: &str) -> Self {
        self.entry = entry.to_string();
        self
    }
}

/// Generates a GNU ld-compatible linker script.
pub fn generate_linker_script(config: &LinkerConfig) -> Result<String, CodegenError> {
    if config.regions.is_empty() {
        return Err(CodegenError::AbiError(
            "linker config has no memory regions".into(),
        ));
    }

    let mut script = String::new();

    // Header
    script.push_str("/* Auto-generated by Fajar Lang compiler */\n\n");

    // Entry point
    script.push_str(&format!("ENTRY({})\n\n", config.entry));

    // Memory regions
    script.push_str("MEMORY\n{\n");
    for region in &config.regions {
        script.push_str(&format!(
            "    {} ({}) : ORIGIN = 0x{:08X}, LENGTH = 0x{:X}\n",
            region.name, region.attrs, region.origin, region.size
        ));
    }
    script.push_str("}\n\n");

    // Find FLASH and RAM regions
    let flash_name = config
        .regions
        .iter()
        .find(|r| r.attrs.contains('x'))
        .map(|r| r.name.as_str())
        .unwrap_or("FLASH");
    let ram_name = config
        .regions
        .iter()
        .find(|r| r.attrs.contains('w') && !r.attrs.contains('x'))
        .or_else(|| config.regions.iter().find(|r| r.attrs.contains('w')))
        .map(|r| r.name.as_str())
        .unwrap_or("RAM");

    // Sections
    script.push_str("SECTIONS\n{\n");

    // .text (code)
    script.push_str(&format!(
        "    .text :\n    {{\n        *(.text.start)\n        *(.text .text.*)\n    }} > {flash_name}\n\n"
    ));

    // .rodata (read-only data)
    script.push_str(&format!(
        "    .rodata :\n    {{\n        *(.rodata .rodata.*)\n    }} > {flash_name}\n\n"
    ));

    // .data (initialized data)
    script.push_str(&format!(
        "    .data :\n    {{\n        __data_start = .;\n        *(.data .data.*)\n        __data_end = .;\n    }} > {ram_name} AT > {flash_name}\n\n"
    ));

    // .bss (zero-initialized data)
    script.push_str(&format!(
        "    .bss :\n    {{\n        __bss_start = .;\n        *(.bss .bss.*)\n        *(COMMON)\n        __bss_end = .;\n    }} > {ram_name}\n\n"
    ));

    // Stack
    script.push_str(&format!(
        "    .stack (NOLOAD) :\n    {{\n        . = ALIGN(16);\n        __stack_bottom = .;\n        . += 0x{:X};\n        __stack_top = .;\n    }} > {ram_name}\n\n",
        config.stack_size
    ));

    // Provide symbols
    script.push_str("    /DISCARD/ :\n    {\n        *(.comment)\n        *(.note*)\n    }\n");

    script.push_str("}\n\n");

    // Stack pointer symbol
    script.push_str("PROVIDE(__stack_ptr = __stack_top);\n");

    Ok(script)
}

/// Generates aarch64 bare-metal startup assembly.
///
/// This stub:
/// 1. Sets the stack pointer from linker symbol `__stack_top`
/// 2. Zeros the BSS section (`__bss_start` to `__bss_end`)
/// 3. Calls the user's entry function (default: `kernel_main`)
/// 4. On return, enters WFE halt loop
pub fn generate_aarch64_startup(entry_fn: &str) -> String {
    format!(
        r#"/* Auto-generated aarch64 bare-metal startup — FajarOS */
.section .text.start, "ax"
.global _start
.type _start, @function

_start:
    /* Set stack pointer */
    ldr     x0, =__stack_top
    mov     sp, x0

    /* Zero BSS section */
    ldr     x0, =__bss_start
    ldr     x1, =__bss_end
.Lbss_loop:
    cmp     x0, x1
    b.ge    .Lbss_done
    str     xzr, [x0], #8
    b       .Lbss_loop
.Lbss_done:

    /* Set VBAR_EL1 to exception vector table */
    ldr     x0, =__vectors
    msr     VBAR_EL1, x0
    isb

    /* Call kernel entry */
    bl      {entry_fn}

    /* Halt loop (should never return) */
.Lhalt:
    wfe
    b       .Lhalt

.size _start, . - _start

/* ═══════════════════════════════════════════════════════════════════
   Exception Vector Table (aarch64 EL1)
   16 entries × 128 bytes each = 2048 bytes, 2KB aligned
   Layout:
     Current EL, SP_EL0:    Sync, IRQ, FIQ, SError
     Current EL, SP_ELx:    Sync, IRQ, FIQ, SError
     Lower EL, AArch64:     Sync, IRQ, FIQ, SError
     Lower EL, AArch32:     Sync, IRQ, FIQ, SError
   ═══════════════════════════════════════════════════════════════════ */

.balign 2048
.global __vectors
__vectors:
    /* Current EL, SP_EL0 — Sync */
    b       __exc_sync_cur
    .balign 128
    /* Current EL, SP_EL0 — IRQ */
    b       __exc_irq_cur
    .balign 128
    /* Current EL, SP_EL0 — FIQ */
    b       __exc_fiq
    .balign 128
    /* Current EL, SP_EL0 — SError */
    b       __exc_serror
    .balign 128

    /* Current EL, SP_ELx — Sync */
    b       __exc_sync_cur
    .balign 128
    /* Current EL, SP_ELx — IRQ */
    b       __exc_irq_cur
    .balign 128
    /* Current EL, SP_ELx — FIQ */
    b       __exc_fiq
    .balign 128
    /* Current EL, SP_ELx — SError */
    b       __exc_serror
    .balign 128

    /* Lower EL, AArch64 — Sync (syscalls come here) */
    b       __exc_sync_lower
    .balign 128
    /* Lower EL, AArch64 — IRQ */
    b       __exc_irq_lower
    .balign 128
    /* Lower EL, AArch64 — FIQ */
    b       __exc_fiq
    .balign 128
    /* Lower EL, AArch64 — SError */
    b       __exc_serror
    .balign 128

    /* Lower EL, AArch32 — Sync */
    b       __exc_sync_lower
    .balign 128
    /* Lower EL, AArch32 — IRQ */
    b       __exc_irq_lower
    .balign 128
    /* Lower EL, AArch32 — FIQ */
    b       __exc_fiq
    .balign 128
    /* Lower EL, AArch32 — SError */
    b       __exc_serror
    .balign 128

/* ─── Exception stubs: save context, call handler, restore ─── */

/* Macro: save all GP registers to stack (256 bytes) */
.macro SAVE_CONTEXT
    sub     sp, sp, #272
    stp     x0, x1, [sp, #0]
    stp     x2, x3, [sp, #16]
    stp     x4, x5, [sp, #32]
    stp     x6, x7, [sp, #48]
    stp     x8, x9, [sp, #64]
    stp     x10, x11, [sp, #80]
    stp     x12, x13, [sp, #96]
    stp     x14, x15, [sp, #112]
    stp     x16, x17, [sp, #128]
    stp     x18, x19, [sp, #144]
    stp     x20, x21, [sp, #160]
    stp     x22, x23, [sp, #176]
    stp     x24, x25, [sp, #192]
    stp     x26, x27, [sp, #208]
    stp     x28, x29, [sp, #224]
    mrs     x0, ELR_EL1
    mrs     x1, SPSR_EL1
    stp     x30, x0, [sp, #240]
    str     x1, [sp, #256]          /* SPSR_EL1 saved! */
.endm

.macro RESTORE_CONTEXT
    ldr     x1, [sp, #256]          /* restore SPSR_EL1 */
    msr     SPSR_EL1, x1
    ldp     x30, x0, [sp, #240]
    msr     ELR_EL1, x0
    ldp     x0, x1, [sp, #0]
    ldp     x2, x3, [sp, #16]
    ldp     x4, x5, [sp, #32]
    ldp     x6, x7, [sp, #48]
    ldp     x8, x9, [sp, #64]
    ldp     x10, x11, [sp, #80]
    ldp     x12, x13, [sp, #96]
    ldp     x14, x15, [sp, #112]
    ldp     x16, x17, [sp, #128]
    ldp     x18, x19, [sp, #144]
    ldp     x20, x21, [sp, #160]
    ldp     x22, x23, [sp, #176]
    ldp     x24, x25, [sp, #192]
    ldp     x26, x27, [sp, #208]
    ldp     x28, x29, [sp, #224]
    add     sp, sp, #272
.endm

/* Sync exception from current EL (includes SVC syscalls) */
.global __exc_sync_cur
__exc_sync_cur:
    SAVE_CONTEXT
    /* Save SP so syscall handlers can read saved registers */
    mov     x3, sp
    movz    x4, #0x1018
    movk    x4, #0x4700, lsl #16
    str     x3, [x4]
    mrs     x0, ESR_EL1     /* x0 = ESR (exception syndrome) */
    mrs     x1, ELR_EL1     /* x1 = ELR (return address) */
    mrs     x2, FAR_EL1     /* x2 = FAR (fault address) */
    bl      fj_exception_sync
    /* Check context switch flag (same as IRQ handler) */
    movz    x0, #0x1010
    movk    x0, #0x4700, lsl #16
    ldr     x1, [x0]
    cbz     x1, 1f
    mov     sp, x1
    str     xzr, [x0]
1:
    RESTORE_CONTEXT
    eret

/* IRQ from current EL — with context switch support */
.global __exc_irq_cur
__exc_irq_cur:
    SAVE_CONTEXT
    /* Save current SP for scheduler */
    mov     x0, sp
    movz    x1, #0x1018
    movk    x1, #0x4700, lsl #16
    str     x0, [x1]
    bl      fj_exception_irq
    /* Check context switch flag at 0x47001010 */
    movz    x0, #0x1010
    movk    x0, #0x4700, lsl #16
    ldr     x1, [x0]
    cbz     x1, 1f
    /* Switch stack to new process */
    mov     sp, x1
    str     xzr, [x0]
1:
    RESTORE_CONTEXT
    eret

/* Sync exception from lower EL (syscalls from EL0) */
.global __exc_sync_lower
__exc_sync_lower:
    SAVE_CONTEXT
    /* Save SP for syscall handlers + context switch */
    mov     x3, sp
    movz    x4, #0x1018
    movk    x4, #0x4700, lsl #16
    str     x3, [x4]
    mrs     x0, ESR_EL1
    mrs     x1, ELR_EL1
    mrs     x2, FAR_EL1
    bl      fj_exception_sync
    /* Check context switch flag (same as cur EL) */
    movz    x0, #0x1010
    movk    x0, #0x4700, lsl #16
    ldr     x1, [x0]
    cbz     x1, 1f
    mov     sp, x1
    str     xzr, [x0]
1:
    RESTORE_CONTEXT
    eret

/* IRQ from lower EL (timer preemption of EL0 processes) */
.global __exc_irq_lower
__exc_irq_lower:
    SAVE_CONTEXT
    /* Save SP for scheduler */
    mov     x0, sp
    movz    x1, #0x1018
    movk    x1, #0x4700, lsl #16
    str     x0, [x1]
    bl      fj_exception_irq
    /* Check context switch flag */
    movz    x0, #0x1010
    movk    x0, #0x4700, lsl #16
    ldr     x1, [x0]
    cbz     x1, 1f
    mov     sp, x1
    str     xzr, [x0]
1:
    RESTORE_CONTEXT
    eret

/* FIQ (unused, halt) */
.global __exc_fiq
__exc_fiq:
    b       __exc_fiq

/* SError (halt) */
.global __exc_serror
__exc_serror:
    b       __exc_serror

/* Bare-metal runtime: volatile I/O */
.global fj_rt_volatile_write
.type fj_rt_volatile_write, @function
fj_rt_volatile_write:
    /* x0 = addr, x1 = value */
    str     x1, [x0]
    ret
.size fj_rt_volatile_write, . - fj_rt_volatile_write

.global fj_rt_volatile_read
.type fj_rt_volatile_read, @function
fj_rt_volatile_read:
    /* x0 = addr, returns value in x0 */
    ldr     x0, [x0]
    ret
.size fj_rt_volatile_read, . - fj_rt_volatile_read

.global fj_rt_volatile_write_u8
.type fj_rt_volatile_write_u8, @function
fj_rt_volatile_write_u8:
    strb    w1, [x0]
    ret
.size fj_rt_volatile_write_u8, . - fj_rt_volatile_write_u8

.global fj_rt_volatile_read_u8
.type fj_rt_volatile_read_u8, @function
fj_rt_volatile_read_u8:
    ldrb    w0, [x0]
    ret
.size fj_rt_volatile_read_u8, . - fj_rt_volatile_read_u8

.global fj_rt_volatile_write_u16
.type fj_rt_volatile_write_u16, @function
fj_rt_volatile_write_u16:
    strh    w1, [x0]
    ret
.size fj_rt_volatile_write_u16, . - fj_rt_volatile_write_u16

.global fj_rt_volatile_read_u16
.type fj_rt_volatile_read_u16, @function
fj_rt_volatile_read_u16:
    ldrh    w0, [x0]
    ret
.size fj_rt_volatile_read_u16, . - fj_rt_volatile_read_u16

.global fj_rt_volatile_write_u32
.type fj_rt_volatile_write_u32, @function
fj_rt_volatile_write_u32:
    str     w1, [x0]
    ret
.size fj_rt_volatile_write_u32, . - fj_rt_volatile_write_u32

.global fj_rt_volatile_read_u32
.type fj_rt_volatile_read_u32, @function
fj_rt_volatile_read_u32:
    ldr     w0, [x0]
    ret
.size fj_rt_volatile_read_u32, . - fj_rt_volatile_read_u32

/* Bare-metal runtime: memcpy/memset/halt */
.global fj_rt_bare_memcpy
.type fj_rt_bare_memcpy, @function
fj_rt_bare_memcpy:
    /* x0=dst, x1=src, x2=n */
    mov     x3, x0
.Lmcpy:
    cbz     x2, .Lmcpy_done
    ldrb    w4, [x1], #1
    strb    w4, [x0], #1
    sub     x2, x2, #1
    b       .Lmcpy
.Lmcpy_done:
    mov     x0, x3
    ret
.size fj_rt_bare_memcpy, . - fj_rt_bare_memcpy

.global fj_rt_bare_memset
.type fj_rt_bare_memset, @function
fj_rt_bare_memset:
    /* x0=dst, x1=val, x2=n */
    mov     x3, x0
.Lmset:
    cbz     x2, .Lmset_done
    strb    w1, [x0], #1
    sub     x2, x2, #1
    b       .Lmset
.Lmset_done:
    mov     x0, x3
    ret
.size fj_rt_bare_memset, . - fj_rt_bare_memset

.global fj_rt_bare_halt
.type fj_rt_bare_halt, @function
fj_rt_bare_halt:
    wfe
    b       fj_rt_bare_halt
.size fj_rt_bare_halt, . - fj_rt_bare_halt

.global fj_rt_bare_print_i64
.type fj_rt_bare_print_i64, @function
fj_rt_bare_print_i64:
    /* Minimal: just write value as single char to UART */
    ldr     x1, =0x09000000
    add     w2, w0, #48   /* convert digit to ASCII (works for 0-9) */
    strb    w2, [x1]
    mov     w2, #10       /* newline */
    strb    w2, [x1]
    ret
.size fj_rt_bare_print_i64, . - fj_rt_bare_print_i64

.global fj_rt_bare_irq_enable
.type fj_rt_bare_irq_enable, @function
fj_rt_bare_irq_enable:
    msr     DAIFClr, #2
    isb
    ret
.size fj_rt_bare_irq_enable, . - fj_rt_bare_irq_enable

.global fj_rt_bare_irq_disable
.type fj_rt_bare_irq_disable, @function
fj_rt_bare_irq_disable:
    msr     DAIFSet, #2
    isb
    ret
.size fj_rt_bare_irq_disable, . - fj_rt_bare_irq_disable

.global fj_rt_bare_print
.type fj_rt_bare_print, @function
fj_rt_bare_print:
    /* x0=ptr, x1=len */
    ldr     x2, =0x09000000
.Lprint:
    cbz     x1, .Lprint_done
    ldrb    w3, [x0], #1
    strb    w3, [x2]
    sub     x1, x1, #1
    b       .Lprint
.Lprint_done:
    ret
.size fj_rt_bare_print, . - fj_rt_bare_print

/* println: print + newline */
.global fj_rt_bare_println
.type fj_rt_bare_println, @function
fj_rt_bare_println:
    /* x0 = ptr, x1 = len — reuse print, then add newline */
    stp     x29, x30, [sp, #-16]!
    bl      fj_rt_bare_print
    mov     w0, #10
    ldr     x1, =0x09000000
    strb    w0, [x1]
    ldp     x29, x30, [sp], #16
    ret
.size fj_rt_bare_println, . - fj_rt_bare_println

/* ═══════════════════════════════════════════════════════════════════
   System register access stubs (workaround for asm! out() codegen bug)
   These functions actually execute mrs/msr instructions and return
   real register values, unlike the asm!() codegen which only encodes.
   ═══════════════════════════════════════════════════════════════════ */

/* Timer */
.global fj_rt_bare_timer_count
.type fj_rt_bare_timer_count, @function
fj_rt_bare_timer_count:
    mrs     x0, CNTPCT_EL0
    ret
.size fj_rt_bare_timer_count, . - fj_rt_bare_timer_count

.global fj_rt_bare_timer_freq
.type fj_rt_bare_timer_freq, @function
fj_rt_bare_timer_freq:
    mrs     x0, CNTFRQ_EL0
    ret
.size fj_rt_bare_timer_freq, . - fj_rt_bare_timer_freq

.global fj_rt_bare_timer_set
.type fj_rt_bare_timer_set, @function
fj_rt_bare_timer_set:
    /* x0 = tval (timer interval in counter ticks) */
    msr     CNTP_TVAL_EL0, x0
    mov     x1, #1
    msr     CNTP_CTL_EL0, x1
    ret
.size fj_rt_bare_timer_set, . - fj_rt_bare_timer_set

.global fj_rt_bare_timer_disable
.type fj_rt_bare_timer_disable, @function
fj_rt_bare_timer_disable:
    msr     CNTP_CTL_EL0, xzr
    ret
.size fj_rt_bare_timer_disable, . - fj_rt_bare_timer_disable

.global fj_rt_bare_timer_status
.type fj_rt_bare_timer_status, @function
fj_rt_bare_timer_status:
    /* Returns CNTP_CTL_EL0 (bit 2 = ISTATUS) */
    mrs     x0, CNTP_CTL_EL0
    ret
.size fj_rt_bare_timer_status, . - fj_rt_bare_timer_status

/* CPU info */
.global fj_rt_bare_read_el
.type fj_rt_bare_read_el, @function
fj_rt_bare_read_el:
    mrs     x0, CurrentEL
    lsr     x0, x0, #2
    and     x0, x0, #3
    ret
.size fj_rt_bare_read_el, . - fj_rt_bare_read_el

.global fj_rt_bare_read_midr
.type fj_rt_bare_read_midr, @function
fj_rt_bare_read_midr:
    mrs     x0, MIDR_EL1
    ret
.size fj_rt_bare_read_midr, . - fj_rt_bare_read_midr

/* MMU */
.global fj_rt_bare_mmu_enable
.type fj_rt_bare_mmu_enable, @function
fj_rt_bare_mmu_enable:
    /* x0 = MAIR, x1 = TCR, x2 = TTBR0 */
    msr     MAIR_EL1, x0
    msr     TCR_EL1, x1
    isb
    msr     TTBR0_EL1, x2
    isb
    /* Flush TLB before enabling (clear stale firmware entries) */
    tlbi    vmalle1is
    dsb     ish
    isb
    mrs     x3, SCTLR_EL1
    orr     x3, x3, #1         /* M = MMU enable */
    orr     x3, x3, #4         /* C = data cache */
    orr     x3, x3, #(1<<12)   /* I = instruction cache */
    bic     x3, x3, #(1<<19)   /* Clear WXN: allow writable+executable */
    msr     SCTLR_EL1, x3
    isb
    ret
.size fj_rt_bare_mmu_enable, . - fj_rt_bare_mmu_enable

/* GIC CPU interface */
.global fj_rt_bare_gic_cpu_init
.type fj_rt_bare_gic_cpu_init, @function
fj_rt_bare_gic_cpu_init:
    /* x0 = PMR value */
    msr     ICC_PMR_EL1, x0
    mov     x1, #1
    msr     ICC_IGRPEN1_EL1, x1
    msr     DAIFClr, #2
    isb
    ret
.size fj_rt_bare_gic_cpu_init, . - fj_rt_bare_gic_cpu_init

.global fj_rt_bare_gic_ack
.type fj_rt_bare_gic_ack, @function
fj_rt_bare_gic_ack:
    mrs     x0, ICC_IAR1_EL1
    ret
.size fj_rt_bare_gic_ack, . - fj_rt_bare_gic_ack

.global fj_rt_bare_gic_eoi
.type fj_rt_bare_gic_eoi, @function
fj_rt_bare_gic_eoi:
    msr     ICC_EOIR1_EL1, x0
    ret
.size fj_rt_bare_gic_eoi, . - fj_rt_bare_gic_eoi

/* ═══════════════════════════════════════════════════════════════════
   Context Switch Builtins (for IRQ handler scheduler integration)
   These use hardcoded addresses to avoid volatile_read/write clobber
   ═══════════════════════════════════════════════════════════════════ */

/* User-mode syscall: svc(num, arg1, arg2) -> result */
/* Sets x0=num, x1=arg1, x2=arg2, executes SVC #0, returns x0 */
.global fj_rt_bare_svc
.type fj_rt_bare_svc, @function
fj_rt_bare_svc:
    /* x0=syscall_num, x1=arg1, x2=arg2 already in correct registers */
    svc     #0
    /* x0 = return value (set by syscall handler via syscall_set_return) */
    ret
.size fj_rt_bare_svc, . - fj_rt_bare_svc

/* TTBR0 switch + TLB flush (for per-process page tables) */
.global fj_rt_bare_switch_ttbr0
.type fj_rt_bare_switch_ttbr0, @function
fj_rt_bare_switch_ttbr0:
    /* x0 = new TTBR0 address */
    msr     TTBR0_EL1, x0
    isb
    tlbi    vmalle1is
    dsb     ish
    isb
    ret
.size fj_rt_bare_switch_ttbr0, . - fj_rt_bare_switch_ttbr0

/* Flush TLB for specific VA (does NOT affect current code page) */
.global fj_rt_bare_tlbi_va
.type fj_rt_bare_tlbi_va, @function
fj_rt_bare_tlbi_va:
    /* x0 = virtual address to flush (shifted right by 12) */
    lsr     x0, x0, #12
    tlbi    vale1is, x0
    dsb     ish
    isb
    ret
.size fj_rt_bare_tlbi_va, . - fj_rt_bare_tlbi_va

/* Read current TTBR0 */
.global fj_rt_bare_read_ttbr0
.type fj_rt_bare_read_ttbr0, @function
fj_rt_bare_read_ttbr0:
    mrs     x0, TTBR0_EL1
    ret
.size fj_rt_bare_read_ttbr0, . - fj_rt_bare_read_ttbr0

/* Syscall: read saved x0 from exception stack (syscall arg 0) */
/* The exception stack has saved registers at known offsets. */
/* saved_sp is at 0x47001018. x0 is at [saved_sp + 0]. */
.global fj_rt_bare_syscall_arg0
.type fj_rt_bare_syscall_arg0, @function
fj_rt_bare_syscall_arg0:
    movz    x1, #0x1018
    movk    x1, #0x4700, lsl #16
    ldr     x1, [x1]           /* x1 = saved_sp */
    ldr     x0, [x1, #0]      /* x0 = saved x0 (arg0) */
    ret
.size fj_rt_bare_syscall_arg0, . - fj_rt_bare_syscall_arg0

.global fj_rt_bare_syscall_arg1
.type fj_rt_bare_syscall_arg1, @function
fj_rt_bare_syscall_arg1:
    movz    x1, #0x1018
    movk    x1, #0x4700, lsl #16
    ldr     x1, [x1]
    ldr     x0, [x1, #8]      /* x0 = saved x1 (arg1) */
    ret
.size fj_rt_bare_syscall_arg1, . - fj_rt_bare_syscall_arg1

.global fj_rt_bare_syscall_arg2
.type fj_rt_bare_syscall_arg2, @function
fj_rt_bare_syscall_arg2:
    movz    x1, #0x1018
    movk    x1, #0x4700, lsl #16
    ldr     x1, [x1]
    ldr     x0, [x1, #16]     /* x0 = saved x2 (arg2) */
    ret
.size fj_rt_bare_syscall_arg2, . - fj_rt_bare_syscall_arg2

/* Syscall: set return value (write to saved x0 on exception stack) */
.global fj_rt_bare_syscall_set_return
.type fj_rt_bare_syscall_set_return, @function
fj_rt_bare_syscall_set_return:
    /* x0 = return value to set */
    movz    x1, #0x1018
    movk    x1, #0x4700, lsl #16
    ldr     x1, [x1]
    str     x0, [x1, #0]      /* saved x0 = return value */
    ret
.size fj_rt_bare_syscall_set_return, . - fj_rt_bare_syscall_set_return

/* Read saved SP from vector stub (0x47001018) */
.global fj_rt_bare_sched_get_saved_sp
.type fj_rt_bare_sched_get_saved_sp, @function
fj_rt_bare_sched_get_saved_sp:
    movz    x1, #0x1018
    movk    x1, #0x4700, lsl #16
    ldr     x0, [x1]
    ret
.size fj_rt_bare_sched_get_saved_sp, . - fj_rt_bare_sched_get_saved_sp

/* Set next SP for context switch (0x47001010) */
.global fj_rt_bare_sched_set_next_sp
.type fj_rt_bare_sched_set_next_sp, @function
fj_rt_bare_sched_set_next_sp:
    /* x0 = new process SP */
    movz    x1, #0x1010
    movk    x1, #0x4700, lsl #16
    str     x0, [x1]
    ret
.size fj_rt_bare_sched_set_next_sp, . - fj_rt_bare_sched_set_next_sp

/* Read/write process table entry (avoids volatile clobber in IRQ) */
/* sched_read_proc(addr) -> value at addr */
.global fj_rt_bare_sched_read_proc
.type fj_rt_bare_sched_read_proc, @function
fj_rt_bare_sched_read_proc:
    ldr     x0, [x0]
    ret
.size fj_rt_bare_sched_read_proc, . - fj_rt_bare_sched_read_proc

/* sched_write_proc(addr, value) */
.global fj_rt_bare_sched_write_proc
.type fj_rt_bare_sched_write_proc, @function
fj_rt_bare_sched_write_proc:
    str     x1, [x0]
    ret
.size fj_rt_bare_sched_write_proc, . - fj_rt_bare_sched_write_proc

/* ═══════════════════════════════════════════════════════════════════
   Phase 3 HAL Driver Stubs (Sprint 11-15)
   GPIO uses TLMM MMIO, UART uses PL011, Timer uses virtual timer regs.
   These are the bare-metal versions; hosted mode uses runtime_bare.rs.
   ═══════════════════════════════════════════════════════════════════ */

/* GPIO: write pin value via QEMU virt GPIO (simulation — real TLMM on Q6A) */
.global fj_rt_bare_gpio_write
.type fj_rt_bare_gpio_write, @function
fj_rt_bare_gpio_write:
    /* x0 = pin, x1 = value (0 or 1) — simulation: nop on QEMU */
    ret
.size fj_rt_bare_gpio_write, . - fj_rt_bare_gpio_write

.global fj_rt_bare_gpio_read
.type fj_rt_bare_gpio_read, @function
fj_rt_bare_gpio_read:
    /* x0 = pin — simulation: return 0 */
    mov     x0, #0
    ret
.size fj_rt_bare_gpio_read, . - fj_rt_bare_gpio_read

/* UART PL011: write byte with FIFO wait */
.global fj_rt_bare_uart_write_byte_asm
.type fj_rt_bare_uart_write_byte_asm, @function
fj_rt_bare_uart_write_byte_asm:
    /* x0 = port (ignored, uses port 0), x1 = byte */
    ldr     x2, =0x09000000
.Luart_tx_wait:
    ldr     w3, [x2, #0x18]         /* UARTFR */
    tbnz    w3, #5, .Luart_tx_wait  /* bit 5 = TXFF (TX FIFO full) */
    strb    w1, [x2]                /* UARTDR */
    ret
.size fj_rt_bare_uart_write_byte_asm, . - fj_rt_bare_uart_write_byte_asm

/* UART PL011: read byte (returns -1 if empty) */
.global fj_rt_bare_uart_read_byte_asm
.type fj_rt_bare_uart_read_byte_asm, @function
fj_rt_bare_uart_read_byte_asm:
    /* x0 = port (ignored) */
    ldr     x2, =0x09000000
    ldr     w3, [x2, #0x18]         /* UARTFR */
    tbnz    w3, #4, .Luart_rx_empty /* bit 4 = RXFE (RX FIFO empty) */
    ldrb    w0, [x2]                /* UARTDR */
    ret
.Luart_rx_empty:
    mov     x0, #-1
    ret
.size fj_rt_bare_uart_read_byte_asm, . - fj_rt_bare_uart_read_byte_asm

/* Virtual timer: set absolute deadline */
.global fj_rt_bare_timer_set_deadline_asm
.type fj_rt_bare_timer_set_deadline_asm, @function
fj_rt_bare_timer_set_deadline_asm:
    /* x0 = absolute tick deadline */
    msr     CNTV_CVAL_EL0, x0
    ret
.size fj_rt_bare_timer_set_deadline_asm, . - fj_rt_bare_timer_set_deadline_asm

/* Virtual timer: enable (ENABLE=1, IMASK=0) */
.global fj_rt_bare_timer_enable_virtual_asm
.type fj_rt_bare_timer_enable_virtual_asm, @function
fj_rt_bare_timer_enable_virtual_asm:
    mov     x0, #1
    msr     CNTV_CTL_EL0, x0
    isb
    ret
.size fj_rt_bare_timer_enable_virtual_asm, . - fj_rt_bare_timer_enable_virtual_asm

/* Virtual timer: disable */
.global fj_rt_bare_timer_disable_virtual_asm
.type fj_rt_bare_timer_disable_virtual_asm, @function
fj_rt_bare_timer_disable_virtual_asm:
    msr     CNTV_CTL_EL0, xzr
    ret
.size fj_rt_bare_timer_disable_virtual_asm, . - fj_rt_bare_timer_disable_virtual_asm

/* Virtual timer: read count */
.global fj_rt_bare_timer_get_ticks_asm
.type fj_rt_bare_timer_get_ticks_asm, @function
fj_rt_bare_timer_get_ticks_asm:
    mrs     x0, CNTVCT_EL0
    ret
.size fj_rt_bare_timer_get_ticks_asm, . - fj_rt_bare_timer_get_ticks_asm

/* Sleep: busy-wait using virtual timer counter */
.global fj_rt_bare_sleep_ms_asm
.type fj_rt_bare_sleep_ms_asm, @function
fj_rt_bare_sleep_ms_asm:
    /* x0 = milliseconds */
    mrs     x1, CNTFRQ_EL0          /* timer frequency */
    mul     x2, x1, x0              /* freq * ms */
    mov     x3, #1000
    udiv    x2, x2, x3              /* wait_ticks = freq * ms / 1000 */
    mrs     x3, CNTVCT_EL0          /* start ticks */
    add     x2, x2, x3              /* end = start + wait_ticks */
.Lsleep_ms_loop:
    wfi                              /* wait for interrupt (saves power) */
    mrs     x4, CNTVCT_EL0
    cmp     x4, x2
    b.lo    .Lsleep_ms_loop
    ret
.size fj_rt_bare_sleep_ms_asm, . - fj_rt_bare_sleep_ms_asm

/* DMA barrier: cache clean + invalidate + DSB */
.global fj_rt_bare_dma_barrier_asm
.type fj_rt_bare_dma_barrier_asm, @function
fj_rt_bare_dma_barrier_asm:
    dsb     sy
    isb
    ret
.size fj_rt_bare_dma_barrier_asm, . - fj_rt_bare_dma_barrier_asm

/* ═══════════════════════════════════════════════════════════════════
   Auto-generated asm! stubs: mrs/msr/barrier
   These actually execute ARM64 instructions and return real values.
   Generated for all system registers in sysreg_encoding().
   ═══════════════════════════════════════════════════════════════════ */

/* MRS stubs: () -> i64 */
.macro MRS_STUB name, sysreg
.global fj_rt_asm_mrs_\name
.type fj_rt_asm_mrs_\name, @function
fj_rt_asm_mrs_\name:
    mrs     x0, \sysreg
    ret
.size fj_rt_asm_mrs_\name, . - fj_rt_asm_mrs_\name
.endm

MRS_STUB sctlr_el1, SCTLR_EL1
MRS_STUB tcr_el1, TCR_EL1
MRS_STUB mair_el1, MAIR_EL1
MRS_STUB ttbr0_el1, TTBR0_EL1
MRS_STUB ttbr1_el1, TTBR1_EL1
MRS_STUB vbar_el1, VBAR_EL1
MRS_STUB esr_el1, ESR_EL1
MRS_STUB far_el1, FAR_EL1
MRS_STUB elr_el1, ELR_EL1
MRS_STUB spsr_el1, SPSR_EL1
MRS_STUB sp_el0, SP_EL0
MRS_STUB daif, DAIF
MRS_STUB currentel, CurrentEL
MRS_STUB icc_iar1_el1, ICC_IAR1_EL1
MRS_STUB icc_pmr_el1, ICC_PMR_EL1
MRS_STUB icc_sre_el1, ICC_SRE_EL1
MRS_STUB icc_ctlr_el1, ICC_CTLR_EL1
MRS_STUB icc_igrpen1_el1, ICC_IGRPEN1_EL1
MRS_STUB cntfrq_el0, CNTFRQ_EL0
MRS_STUB cntpct_el0, CNTPCT_EL0
MRS_STUB cntp_tval_el0, CNTP_TVAL_EL0
MRS_STUB cntp_ctl_el0, CNTP_CTL_EL0
MRS_STUB cntvct_el0, CNTVCT_EL0
MRS_STUB cntv_tval_el0, CNTV_TVAL_EL0
MRS_STUB cntv_ctl_el0, CNTV_CTL_EL0
MRS_STUB midr_el1, MIDR_EL1

/* MSR stubs: (i64) -> void */
.macro MSR_STUB name, sysreg
.global fj_rt_asm_msr_\name
.type fj_rt_asm_msr_\name, @function
fj_rt_asm_msr_\name:
    msr     \sysreg, x0
    ret
.size fj_rt_asm_msr_\name, . - fj_rt_asm_msr_\name
.endm

MSR_STUB sctlr_el1, SCTLR_EL1
MSR_STUB tcr_el1, TCR_EL1
MSR_STUB mair_el1, MAIR_EL1
MSR_STUB ttbr0_el1, TTBR0_EL1
MSR_STUB ttbr1_el1, TTBR1_EL1
MSR_STUB vbar_el1, VBAR_EL1
MSR_STUB elr_el1, ELR_EL1
MSR_STUB spsr_el1, SPSR_EL1
MSR_STUB daif, DAIF
MSR_STUB icc_pmr_el1, ICC_PMR_EL1
MSR_STUB icc_eoir1_el1, ICC_EOIR1_EL1
MSR_STUB icc_igrpen1_el1, ICC_IGRPEN1_EL1
MSR_STUB cntp_tval_el0, CNTP_TVAL_EL0
MSR_STUB cntp_ctl_el0, CNTP_CTL_EL0
MSR_STUB cntv_tval_el0, CNTV_TVAL_EL0
MSR_STUB cntv_ctl_el0, CNTV_CTL_EL0
MSR_STUB sp_el0, SP_EL0

/* Barrier/control stubs: () -> void */
.global fj_rt_asm_isb
.type fj_rt_asm_isb, @function
fj_rt_asm_isb:
    isb
    ret
.size fj_rt_asm_isb, . - fj_rt_asm_isb

.global fj_rt_asm_dsb
.type fj_rt_asm_dsb, @function
fj_rt_asm_dsb:
    dsb     sy
    ret
.size fj_rt_asm_dsb, . - fj_rt_asm_dsb

.global fj_rt_asm_dmb
.type fj_rt_asm_dmb, @function
fj_rt_asm_dmb:
    dmb     sy
    ret
.size fj_rt_asm_dmb, . - fj_rt_asm_dmb

.global fj_rt_asm_wfe
.type fj_rt_asm_wfe, @function
fj_rt_asm_wfe:
    wfe
    ret
.size fj_rt_asm_wfe, . - fj_rt_asm_wfe

.global fj_rt_asm_wfi
.type fj_rt_asm_wfi, @function
fj_rt_asm_wfi:
    wfi
    ret
.size fj_rt_asm_wfi, . - fj_rt_asm_wfi

.global fj_rt_asm_svc
.type fj_rt_asm_svc, @function
fj_rt_asm_svc:
    svc     #0
    ret
.size fj_rt_asm_svc, . - fj_rt_asm_svc

.global fj_rt_asm_nop
.type fj_rt_asm_nop, @function
fj_rt_asm_nop:
    nop
    ret
.size fj_rt_asm_nop, . - fj_rt_asm_nop

.global fj_rt_asm_eret
.type fj_rt_asm_eret, @function
fj_rt_asm_eret:
    eret
.size fj_rt_asm_eret, . - fj_rt_asm_eret
"#
    )
}

// ═══════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════

/// Generates x86_64 bare-metal startup assembly with Multiboot2 header.
///
/// This stub:
/// 1. Provides a Multiboot2 header (magic 0xE85250D6) so GRUB2 can boot us
/// 2. Sets the stack pointer from linker symbol `__stack_top`
/// 3. Zeros the BSS section (`__bss_start` to `__bss_end`)
/// 4. Initializes the 16550 UART at COM1 (0x3F8) for serial output
/// 5. Calls the user's entry function (default: `kernel_main`)
/// 6. On return, enters CLI+HLT halt loop
///
/// The generated ELF can be booted by:
/// - GRUB2: `multiboot2 /boot/fajaros.elf`
/// - QEMU direct: `qemu-system-x86_64 -kernel fajaros.elf`
///
/// When loaded by Multiboot2-compliant bootloader:
/// - EAX = 0x36D76289 (Multiboot2 magic)
/// - EBX = physical address of Multiboot2 info struct
/// - CPU is already in 64-bit long mode (if using GRUB2 x86_64)
/// - Paging enabled (identity-mapped)
/// - Interrupts disabled
pub fn generate_x86_64_startup(entry_fn: &str) -> String {
    format!(
        r#"/* Auto-generated x86_64 bare-metal startup — FajarOS Nova */
.intel_syntax noprefix

/* ═══════════════════════════════════════════════════════════════════
   Multiboot2 Header
   Must be within the first 32KB of the kernel image.
   Magic: 0xE85250D6, Architecture: 0 (i386, used for x86_64 too)
   ═══════════════════════════════════════════════════════════════════ */
.section .multiboot_header, "a"
.align 8
multiboot_header_start:
    .long   0xE85250D6                              /* magic */
    .long   0                                        /* architecture: 0 = i386/x86_64 */
    .long   multiboot_header_end - multiboot_header_start   /* header length */
    .long   -(0xE85250D6 + 0 + (multiboot_header_end - multiboot_header_start))  /* checksum */

    /* Address tag (type=2): tell GRUB where to load us */
    .align  8
    .short  2       /* type = address */
    .short  0       /* flags */
    .long   24      /* size */
    .long   multiboot_header_start  /* header_addr */
    .long   0x100000                /* load_addr (1MB) */
    .long   0                       /* load_end_addr (0 = load entire file) */
    .long   0                       /* bss_end_addr (0 = no BSS) */

    /* Entry address tag (type=3): tell GRUB where to jump */
    .align  8
    .short  3       /* type = entry_addr */
    .short  0       /* flags */
    .long   12      /* size */
    .long   _start  /* entry_addr (32-bit!) */

    /* End tag (type=0, flags=0, size=8) */
    .align  8
    .short  0       /* type */
    .short  0       /* flags */
    .long   8       /* size */
multiboot_header_end:

/* ═══════════════════════════════════════════════════════════════════
   Entry Point
   GRUB loads us in protected mode (32-bit) or long mode (64-bit)
   depending on config. We handle 64-bit long mode (standard GRUB2).
   QEMU -kernel loads us directly in long mode with identity paging.
   ═══════════════════════════════════════════════════════════════════ */
.section .text.start, "ax"
.global _start
.type _start, @function

/* ═══════════════════════════════════════════════════════════════════
   32-bit Entry (Multiboot2 loads us in 32-bit protected mode)
   Transition: 32-bit protected → 64-bit long mode
   ═══════════════════════════════════════════════════════════════════ */
/* ═══════════════════════════════════════════════════════════════════
   32-bit trampoline encoded as raw bytes to avoid assembler encoding
   issues when building an ELF64 with .code32 sections.

   Instructions (32-bit protected mode, Intel syntax):
     cli
     mov esp, 0x200000           ; temporary stack
     mov edi, ebx                ; save multiboot2 info ptr
     ; Serial output 'N','o','v','a','\n' to COM1 (0x3F8)
     mov dx, 0x3F8 / mov al, byte / out dx, al  (×5)
     ; Page tables at 0x800000 (PML4→PDPT→PD, identity map 0-4MB)
     ; Enable PAE, LME, PG → long mode active
     ; lgdt + far jmp to _start64 in 64-bit segment
   ═══════════════════════════════════════════════════════════════════ */
_start:
    /* cli */
    .byte 0xFA
    /* mov esp, 0x00200000 */
    .byte 0xBC, 0x00, 0x00, 0x20, 0x00
    /* mov edi, ebx */
    .byte 0x89, 0xDF

    /* --- Early serial: write "[BOOT32]\n" to COM1 --- */
    /* mov dx, 0x3F8 ; then mov al, byte ; out dx, al for each char */
    .byte 0x66, 0xBA, 0xF8, 0x03
    .byte 0xB0, 0x5B, 0xEE         /* '[' */
    .byte 0xB0, 0x42, 0xEE         /* 'B' */
    .byte 0xB0, 0x4F, 0xEE         /* 'O' */
    .byte 0xB0, 0x4F, 0xEE         /* 'O' */
    .byte 0xB0, 0x54, 0xEE         /* 'T' */
    .byte 0xB0, 0x33, 0xEE         /* '3' */
    .byte 0xB0, 0x32, 0xEE         /* '2' */
    .byte 0xB0, 0x5D, 0xEE         /* ']' */
    .byte 0xB0, 0x0A, 0xEE         /* '\n' */

    /* --- Zero 12KB at 0x70000 for page tables --- */
    /* Page tables: PML4 at 0x70000, PDPT at 0x71000, PD at 0x72000 */
    /* xor eax, eax */
    .byte 0x31, 0xC0
    /* mov edi, 0x70000 */
    .byte 0xBF, 0x00, 0x00, 0x07, 0x00
    /* mov ecx, 0xC00 (3 pages × 4096/4 = 3072 dwords) */
    .byte 0xB9, 0x00, 0x0C, 0x00, 0x00
    /* cld ; rep stosd */
    .byte 0xFC, 0xF3, 0xAB

    /* --- Set up page tables --- */
    /* PML4[0] → PDPT at 0x71000 (present+write = 0x03) */
    /* mov eax, 0x70000 */
    .byte 0xB8, 0x00, 0x00, 0x07, 0x00
    /* mov dword [eax], 0x71003 */
    .byte 0xC7, 0x00, 0x03, 0x10, 0x07, 0x00

    /* PDPT[0] → PD at 0x72000 */
    /* mov eax, 0x71000 */
    .byte 0xB8, 0x00, 0x10, 0x07, 0x00
    /* mov dword [eax], 0x72003 */
    .byte 0xC7, 0x00, 0x03, 0x20, 0x07, 0x00

    /* PD[0] → 0x0 (2MB huge page, present+write+huge = 0x83) */
    /* mov eax, 0x72000 */
    .byte 0xB8, 0x00, 0x20, 0x07, 0x00
    /* mov dword [eax], 0x83 */
    .byte 0xC7, 0x00, 0x83, 0x00, 0x00, 0x00
    /* PD[1] → 0x200000 (2nd 2MB block) */
    /* mov dword [eax+8], 0x200083 */
    .byte 0xC7, 0x40, 0x08, 0x83, 0x00, 0x20, 0x00

    /* --- Load PML4 into CR3 --- */
    /* mov eax, 0x70000 */
    .byte 0xB8, 0x00, 0x00, 0x07, 0x00
    /* mov cr3, eax */
    .byte 0x0F, 0x22, 0xD8

    /* --- Enable PAE (CR4 bit 5) --- */
    /* mov eax, cr4 */
    .byte 0x0F, 0x20, 0xE0
    /* or eax, 0x20 */
    .byte 0x83, 0xC8, 0x20
    /* mov cr4, eax */
    .byte 0x0F, 0x22, 0xE0

    /* --- Enable long mode (EFER.LME, bit 8) --- */
    /* mov ecx, 0xC0000080 */
    .byte 0xB9, 0x80, 0x00, 0x00, 0xC0
    /* rdmsr */
    .byte 0x0F, 0x32
    /* or eax, 0x100 */
    .byte 0x0D, 0x00, 0x01, 0x00, 0x00
    /* wrmsr */
    .byte 0x0F, 0x30

    /* --- Enable paging (CR0 bit 31) → long mode active --- */
    /* mov eax, cr0 */
    .byte 0x0F, 0x20, 0xC0
    /* or eax, 0x80000000 */
    .byte 0x0D, 0x00, 0x00, 0x00, 0x80
    /* mov cr0, eax */
    .byte 0x0F, 0x22, 0xC0

    /* --- Load GDT and far jump to 64-bit code --- */
    /* lgdt [__gdt64_ptr] — address filled by linker */
    .byte 0x0F, 0x01, 0x15
    .long __gdt64_ptr

    /* jmp far 0x08:_start64 */
    .byte 0xEA
    .long _start64
    .word 0x0008

/* Minimal 64-bit GDT */
.align 16
__gdt64:
    .quad 0x0000000000000000    /* null */
    .quad 0x00AF9A000000FFFF    /* code64: L=1, D=0, P=1, DPL=0, S=1, type=A (exec/read) */
    .quad 0x00CF92000000FFFF    /* data64: P=1, DPL=0, S=1, type=2 (read/write) */
__gdt64_ptr:
    .word __gdt64_ptr - __gdt64 - 1
    .long __gdt64

/* ═══════════════════════════════════════════════════════════════════
   64-bit Entry (after long mode transition)
   ═══════════════════════════════════════════════════════════════════ */
.code64
_start64:
    /* Reload data segments with 64-bit data selector */
    mov     ax, 0x10
    mov     ds, ax
    mov     es, ax
    mov     fs, ax
    mov     gs, ax
    mov     ss, ax

    /* Set proper stack pointer: RAM starts at 0x2000000, stack at end of 64MB */
    /* __stack_top = RAM_ORIGIN + RAM_SIZE = 0x2000000 + 0x4000000 = 0x6000000 */
    /* Actually stack is at RAM + 0x4000 (16KB after BSS) */
    mov     rsp, 0x3F0000      /* Stack at ~4MB, within mapped 0-4MB range */

    /* Save Multiboot2 info pointer */
    mov     r12, rdi

    /* BSS is small in bare-metal — kernel_main() handles init */
    /* Skip BSS zeroing here (Cranelift _start wrapper already zeros BSS) */

    /* Initialize COM1 serial (16550 UART at 0x3F8) for debug output */
    mov     dx, 0x3F9           /* IER: disable all interrupts */
    xor     al, al
    out     dx, al

    mov     dx, 0x3FB           /* LCR: enable DLAB */
    mov     al, 0x80
    out     dx, al

    mov     dx, 0x3F8           /* DLL: divisor low = 1 (115200 baud) */
    mov     al, 0x01
    out     dx, al

    mov     dx, 0x3F9           /* DLH: divisor high = 0 */
    xor     al, al
    out     dx, al

    mov     dx, 0x3FB           /* LCR: 8N1, disable DLAB */
    mov     al, 0x03
    out     dx, al

    mov     dx, 0x3FA           /* FCR: enable FIFO, clear, 14-byte threshold */
    mov     al, 0xC7
    out     dx, al

    mov     dx, 0x3FC           /* MCR: RTS + DTR + OUT2 */
    mov     al, 0x0B
    out     dx, al

    /* Call kernel entry */
    call    {entry_fn}

    /* Halt loop (should never return) */
.Lhalt:
    cli
    hlt
    jmp     .Lhalt

.size _start, . - _start

/* ═══════════════════════════════════════════════════════════════════
   Runtime Functions (x86_64 bare-metal)
   These provide the minimal runtime needed by compiled Fajar Lang code.
   ═══════════════════════════════════════════════════════════════════ */

/* port_outb(port: rdi, value: rsi) -> rax=0 */
.global fj_rt_bare_port_outb
.type fj_rt_bare_port_outb, @function
fj_rt_bare_port_outb:
    mov     dx, di              /* port number → DX */
    mov     al, sil             /* value → AL */
    out     dx, al              /* write byte to I/O port */
    xor     eax, eax            /* return 0 */
    ret
.size fj_rt_bare_port_outb, . - fj_rt_bare_port_outb

/* port_inb(port: rdi) -> rax=byte */
.global fj_rt_bare_port_inb
.type fj_rt_bare_port_inb, @function
fj_rt_bare_port_inb:
    mov     dx, di              /* port number → DX */
    xor     eax, eax
    in      al, dx              /* read byte from I/O port → AL */
    ret
.size fj_rt_bare_port_inb, . - fj_rt_bare_port_inb

/* x86_serial_init(port: rdi, baud: rsi) -> rax=0 */
.global fj_rt_bare_x86_serial_init
.type fj_rt_bare_x86_serial_init, @function
fj_rt_bare_x86_serial_init:
    /* port 0 = 0x3F8 (COM1), port 1 = 0x2F8 (COM2) */
    cmp     rdi, 0
    je      .Lserial_com1
    cmp     rdi, 1
    je      .Lserial_com2
    mov     rax, -1
    ret
.Lserial_com1:
    mov     r8, 0x3F8
    jmp     .Lserial_init
.Lserial_com2:
    mov     r8, 0x2F8
.Lserial_init:
    /* divisor = 115200 / baud */
    mov     rax, 115200
    xor     rdx, rdx
    div     rsi                 /* rax = divisor */
    mov     r9, rax             /* save divisor */

    /* Disable interrupts */
    lea     rdx, [r8 + 1]
    xor     al, al
    out     dx, al

    /* Enable DLAB */
    lea     rdx, [r8 + 3]
    mov     al, 0x80
    out     dx, al

    /* Set divisor low */
    mov     rdx, r8
    mov     al, r9b
    out     dx, al

    /* Set divisor high */
    lea     rdx, [r8 + 1]
    mov     al, 0
    out     dx, al

    /* 8N1, disable DLAB */
    lea     rdx, [r8 + 3]
    mov     al, 0x03
    out     dx, al

    /* Enable FIFO */
    lea     rdx, [r8 + 2]
    mov     al, 0xC7
    out     dx, al

    /* MCR: RTS + DTR + OUT2 */
    lea     rdx, [r8 + 4]
    mov     al, 0x0B
    out     dx, al

    xor     eax, eax
    ret
.size fj_rt_bare_x86_serial_init, . - fj_rt_bare_x86_serial_init

/* set_uart_mode_x86(base_port: rdi) -> void */
.global fj_rt_bare_set_uart_mode_x86
.type fj_rt_bare_set_uart_mode_x86, @function
fj_rt_bare_set_uart_mode_x86:
    ret
.size fj_rt_bare_set_uart_mode_x86, . - fj_rt_bare_set_uart_mode_x86

/* fj_rt_bare_print(ptr: rdi, len: rsi) -> void */
/* Outputs bytes to COM1 serial port */
.global fj_rt_bare_print
.type fj_rt_bare_print, @function
fj_rt_bare_print:
    test    rdi, rdi
    jz      .Lprint_done
    test    rsi, rsi
    jle     .Lprint_done
    mov     rcx, rsi            /* count */
    mov     r8, rdi             /* buffer pointer */
.Lprint_loop:
    /* Wait for TX ready (LSR bit 5) */
    mov     dx, 0x3FD
.Lprint_wait:
    in      al, dx
    test    al, 0x20
    jz      .Lprint_wait
    /* Send byte */
    mov     dx, 0x3F8
    mov     al, [r8]
    out     dx, al
    inc     r8
    dec     rcx
    jnz     .Lprint_loop
.Lprint_done:
    ret
.size fj_rt_bare_print, . - fj_rt_bare_print

/* fj_rt_bare_println(ptr: rdi, len: rsi) -> void */
.global fj_rt_bare_println
.type fj_rt_bare_println, @function
fj_rt_bare_println:
    call    fj_rt_bare_print
    /* Send newline */
    mov     dx, 0x3FD
.Lprintln_wait:
    in      al, dx
    test    al, 0x20
    jz      .Lprintln_wait
    mov     dx, 0x3F8
    mov     al, 0x0A
    out     dx, al
    ret
.size fj_rt_bare_println, . - fj_rt_bare_println

/* fj_rt_bare_print_i64(val: rdi) -> void */
/* Print integer as decimal string to COM1 */
.global fj_rt_bare_print_i64
.type fj_rt_bare_print_i64, @function
fj_rt_bare_print_i64:
    push    rbx
    push    r12
    sub     rsp, 24             /* buffer for digits */
    mov     r12, rsp
    mov     rbx, rdi
    lea     rcx, [rsp + 20]     /* end of buffer */
    mov     byte ptr [rcx], 0x0A   /* newline at end */

    /* Handle zero */
    test    rbx, rbx
    jnz     .Lnot_zero
    dec     rcx
    mov     byte ptr [rcx], 0x30  /* '0' */
    jmp     .Lprint_digits

    /* Handle negative */
.Lnot_zero:
    mov     rax, rbx
    test    rax, rax
    jns     .Lpositive
    neg     rax
    mov     rbx, rax
    mov     byte ptr [r12], 0x2D  /* '-' prefix handled later */

.Lpositive:
    mov     rax, rbx
.Ldigit_loop:
    xor     rdx, rdx
    mov     rbx, 10
    div     rbx
    add     dl, 0x30            /* digit → ASCII */
    dec     rcx
    mov     [rcx], dl
    test    rax, rax
    jnz     .Ldigit_loop

.Lprint_digits:
    /* Print from rcx to rsp+21 */
    mov     rdi, rcx
    lea     rsi, [rsp + 21]
    sub     rsi, rcx
    call    fj_rt_bare_print

    add     rsp, 24
    pop     r12
    pop     rbx
    ret
.size fj_rt_bare_print_i64, . - fj_rt_bare_print_i64

/* fj_rt_bare_halt() -> noreturn */
.global fj_rt_bare_halt
.type fj_rt_bare_halt, @function
fj_rt_bare_halt:
    cli
    hlt
    jmp     fj_rt_bare_halt
.size fj_rt_bare_halt, . - fj_rt_bare_halt

/* fj_rt_bare_panic() -> noreturn */
.global fj_rt_bare_panic
.type fj_rt_bare_panic, @function
fj_rt_bare_panic:
    lea     rdi, [rip + .Lpanic_msg]
    mov     rsi, 19
    call    fj_rt_bare_print
    jmp     fj_rt_bare_halt
.Lpanic_msg:
    .ascii  "PANIC: kernel halt\n"
.size fj_rt_bare_panic, . - fj_rt_bare_panic

/* fj_rt_bare_memcpy(dst: rdi, src: rsi, n: rdx) -> rax=dst */
.global fj_rt_bare_memcpy
.type fj_rt_bare_memcpy, @function
fj_rt_bare_memcpy:
    mov     rax, rdi
    mov     rcx, rdx
    cld
    rep     movsb
    ret
.size fj_rt_bare_memcpy, . - fj_rt_bare_memcpy

/* fj_rt_bare_memset(dst: rdi, val: rsi, n: rdx) -> rax=dst */
.global fj_rt_bare_memset
.type fj_rt_bare_memset, @function
fj_rt_bare_memset:
    mov     rax, rdi
    mov     rcx, rdx
    mov     al, sil
    cld
    rep     stosb
    mov     rax, rdi
    ret
.size fj_rt_bare_memset, . - fj_rt_bare_memset

/* volatile_write(addr: rdi, value: rsi) -> void */
.global fj_rt_volatile_write
.type fj_rt_volatile_write, @function
fj_rt_volatile_write:
    mov     [rdi], rsi
    ret
.size fj_rt_volatile_write, . - fj_rt_volatile_write

/* volatile_read(addr: rdi) -> rax */
.global fj_rt_volatile_read
.type fj_rt_volatile_read, @function
fj_rt_volatile_read:
    mov     rax, [rdi]
    ret
.size fj_rt_volatile_read, . - fj_rt_volatile_read

/* volatile_write_u8(addr: rdi, value: rsi) -> void */
.global fj_rt_volatile_write_u8
.type fj_rt_volatile_write_u8, @function
fj_rt_volatile_write_u8:
    mov     [rdi], sil
    ret
.size fj_rt_volatile_write_u8, . - fj_rt_volatile_write_u8

/* volatile_read_u8(addr: rdi) -> rax */
.global fj_rt_volatile_read_u8
.type fj_rt_volatile_read_u8, @function
fj_rt_volatile_read_u8:
    xor     eax, eax
    mov     al, [rdi]
    ret
.size fj_rt_volatile_read_u8, . - fj_rt_volatile_read_u8

/* volatile_write_u16(addr: rdi, value: rsi) -> void */
.global fj_rt_volatile_write_u16
.type fj_rt_volatile_write_u16, @function
fj_rt_volatile_write_u16:
    mov     [rdi], si
    ret
.size fj_rt_volatile_write_u16, . - fj_rt_volatile_write_u16

/* volatile_read_u16(addr: rdi) -> rax */
.global fj_rt_volatile_read_u16
.type fj_rt_volatile_read_u16, @function
fj_rt_volatile_read_u16:
    xor     eax, eax
    mov     ax, [rdi]
    ret
.size fj_rt_volatile_read_u16, . - fj_rt_volatile_read_u16

/* volatile_write_u32(addr: rdi, value: rsi) -> void */
.global fj_rt_volatile_write_u32
.type fj_rt_volatile_write_u32, @function
fj_rt_volatile_write_u32:
    mov     [rdi], esi
    ret
.size fj_rt_volatile_write_u32, . - fj_rt_volatile_write_u32

/* volatile_read_u32(addr: rdi) -> rax */
.global fj_rt_volatile_read_u32
.type fj_rt_volatile_read_u32, @function
fj_rt_volatile_read_u32:
    xor     eax, eax
    mov     eax, [rdi]
    ret
.size fj_rt_volatile_read_u32, . - fj_rt_volatile_read_u32

/* fj_rt_bare_alloc(size: rdi) -> rax (bump allocator) */
/* Simple bump allocator starting at 0x300000 (3MB), grows up to 0x3E0000 */
.global fj_rt_bare_alloc
.type fj_rt_bare_alloc, @function
fj_rt_bare_alloc:
    /* Load current bump pointer from fixed location 0x6FF00 */
    mov     rax, [0x6FF00]
    test    rax, rax
    jnz     .Lalloc_bump
    /* First call: initialize to 0x300000 */
    mov     rax, 0x300000
.Lalloc_bump:
    /* Align size to 8 bytes */
    lea     rcx, [rdi + 7]
    and     rcx, -8
    /* New bump = current + aligned_size */
    lea     rdx, [rax + rcx]
    cmp     rdx, 0x3E0000       /* Check OOM (max ~900KB heap) */
    ja      .Lalloc_oom
    mov     [0x6FF00], rdx       /* Store new bump */
    ret
.Lalloc_oom:
    xor     eax, eax             /* Return 0 (null) */
    ret
.size fj_rt_bare_alloc, . - fj_rt_bare_alloc

/* fj_rt_bare_free — no-op for bump allocator */
.global fj_rt_bare_free
.type fj_rt_bare_free, @function
fj_rt_bare_free:
    ret
.size fj_rt_bare_free, . - fj_rt_bare_free

/* IRQ enable/disable stubs */
.global fj_rt_bare_irq_enable
fj_rt_bare_irq_enable:
    sti
    ret

.global fj_rt_bare_irq_disable
fj_rt_bare_irq_disable:
    cli
    ret

/* Stubs for ARM64-specific builtins (no-op on x86_64) */
.global fj_rt_bare_timer_count
.global fj_rt_bare_timer_freq
.global fj_rt_bare_timer_status
.global fj_rt_bare_read_el
.global fj_rt_bare_read_midr
.global fj_rt_bare_gic_ack
.global fj_rt_bare_timer_set
.global fj_rt_bare_timer_disable
.global fj_rt_bare_gic_eoi
.global fj_rt_bare_gic_cpu_init
.global fj_rt_bare_mmu_enable
.global fj_rt_bare_switch_ttbr0
.global fj_rt_bare_read_ttbr0
.global fj_rt_bare_tlbi_va
.global fj_rt_bare_svc
fj_rt_bare_timer_count:
fj_rt_bare_timer_freq:
fj_rt_bare_timer_status:
fj_rt_bare_read_el:
fj_rt_bare_read_midr:
fj_rt_bare_gic_ack:
fj_rt_bare_read_ttbr0:
    xor     eax, eax
    ret
fj_rt_bare_timer_set:
fj_rt_bare_timer_disable:
fj_rt_bare_gic_eoi:
fj_rt_bare_gic_cpu_init:
fj_rt_bare_mmu_enable:
fj_rt_bare_switch_ttbr0:
fj_rt_bare_tlbi_va:
fj_rt_bare_svc:
    ret

/* GNU stack note — mark as non-executable */
.section .note.GNU-stack, "", @progbits
"#,
        entry_fn = entry_fn
    )
}

/// Generates x86_64 linker script with Multiboot2 header section.
///
/// This extends the standard linker script to place the `.multiboot_header`
/// section at the very beginning of the binary (within first 32KB).
pub fn generate_x86_64_linker_script(config: &LinkerConfig) -> Result<String, CodegenError> {
    if config.regions.is_empty() {
        return Err(CodegenError::AbiError(
            "linker config has no memory regions".into(),
        ));
    }

    let mut script = String::new();

    script.push_str("/* Auto-generated by Fajar Lang compiler — FajarOS Nova x86_64 */\n\n");
    script.push_str(&format!("ENTRY({})\n\n", config.entry));

    // Memory regions
    script.push_str("MEMORY\n{\n");
    for region in &config.regions {
        script.push_str(&format!(
            "    {} ({}) : ORIGIN = 0x{:08X}, LENGTH = 0x{:X}\n",
            region.name, region.attrs, region.origin, region.size
        ));
    }
    script.push_str("}\n\n");

    let flash_name = config
        .regions
        .iter()
        .find(|r| r.attrs.contains('x'))
        .map(|r| r.name.as_str())
        .unwrap_or("FLASH");
    let ram_name = config
        .regions
        .iter()
        .find(|r| r.attrs.contains('w') && !r.attrs.contains('x'))
        .or_else(|| config.regions.iter().find(|r| r.attrs.contains('w')))
        .map(|r| r.name.as_str())
        .unwrap_or("RAM");

    script.push_str("SECTIONS\n{\n");

    // Multiboot2 header MUST be first (within 32KB)
    script.push_str(&format!(
        "    .multiboot_header :\n    {{\n        KEEP(*(.multiboot_header))\n    }} > {flash_name}\n\n"
    ));

    // .text (code) — .text.start comes first (contains _start)
    script.push_str(&format!(
        "    .text :\n    {{\n        *(.text.start)\n        *(.text .text.*)\n    }} > {flash_name}\n\n"
    ));

    // .rodata
    script.push_str(&format!(
        "    .rodata :\n    {{\n        *(.rodata .rodata.*)\n    }} > {flash_name}\n\n"
    ));

    // .data
    script.push_str(&format!(
        "    .data :\n    {{\n        __data_start = .;\n        *(.data .data.*)\n        __data_end = .;\n    }} > {ram_name} AT > {flash_name}\n\n"
    ));

    // .bss
    script.push_str(&format!(
        "    .bss :\n    {{\n        __bss_start = .;\n        *(.bss .bss.*)\n        *(COMMON)\n        __bss_end = .;\n    }} > {ram_name}\n\n"
    ));

    // Stack (16-byte aligned for x86_64 ABI)
    script.push_str(&format!(
        "    .stack (NOLOAD) :\n    {{\n        . = ALIGN(16);\n        __stack_bottom = .;\n        . += 0x{:X};\n        __stack_top = .;\n    }} > {ram_name}\n\n",
        config.stack_size
    ));

    script.push_str("    /DISCARD/ :\n    {\n        *(.comment)\n        *(.note*)\n    }\n");
    script.push_str("}\n\n");
    script.push_str("PROVIDE(__stack_ptr = __stack_top);\n");

    Ok(script)
}

/// Generates an ARM64 assembly wrapper for an `@interrupt` function.
///
/// The wrapper saves all general-purpose registers (x0-x30), calls the
/// Cranelift-compiled handler function, restores registers, and returns
/// via `eret` (exception return) instead of `ret`.
///
/// Usage: include the generated assembly in the AOT compilation output.
/// The wrapper symbol is `__interrupt_{fn_name}` and should be placed
/// in the vector table instead of the raw function.
pub fn generate_interrupt_wrapper(fn_name: &str) -> String {
    format!(
        r#"
/* @interrupt wrapper for {fn_name} — auto-generated */
.global __interrupt_{fn_name}
.type __interrupt_{fn_name}, @function
__interrupt_{fn_name}:
    /* Save all GP registers (272 bytes: x0-x30 + SP + SPSR + ELR) */
    sub     sp, sp, #272
    stp     x0,  x1,  [sp, #0]
    stp     x2,  x3,  [sp, #16]
    stp     x4,  x5,  [sp, #32]
    stp     x6,  x7,  [sp, #48]
    stp     x8,  x9,  [sp, #64]
    stp     x10, x11, [sp, #80]
    stp     x12, x13, [sp, #96]
    stp     x14, x15, [sp, #112]
    stp     x16, x17, [sp, #128]
    stp     x18, x19, [sp, #144]
    stp     x20, x21, [sp, #160]
    stp     x22, x23, [sp, #176]
    stp     x24, x25, [sp, #192]
    stp     x26, x27, [sp, #208]
    stp     x28, x29, [sp, #224]
    str     x30,      [sp, #240]
    mrs     x0, SPSR_EL1
    str     x0,       [sp, #248]
    mrs     x0, ELR_EL1
    str     x0,       [sp, #256]

    /* Call the actual handler */
    bl      {fn_name}

    /* Restore ELR and SPSR */
    ldr     x0,       [sp, #256]
    msr     ELR_EL1, x0
    ldr     x0,       [sp, #248]
    msr     SPSR_EL1, x0

    /* Restore all GP registers */
    ldp     x0,  x1,  [sp, #0]
    ldp     x2,  x3,  [sp, #16]
    ldp     x4,  x5,  [sp, #32]
    ldp     x6,  x7,  [sp, #48]
    ldp     x8,  x9,  [sp, #64]
    ldp     x10, x11, [sp, #80]
    ldp     x12, x13, [sp, #96]
    ldp     x14, x15, [sp, #112]
    ldp     x16, x17, [sp, #128]
    ldp     x18, x19, [sp, #144]
    ldp     x20, x21, [sp, #160]
    ldp     x22, x23, [sp, #176]
    ldp     x24, x25, [sp, #192]
    ldp     x26, x27, [sp, #208]
    ldp     x28, x29, [sp, #224]
    ldr     x30,      [sp, #240]
    add     sp, sp, #272

    /* Exception return (not ret) */
    eret
.size __interrupt_{fn_name}, . - __interrupt_{fn_name}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> LinkerConfig {
        LinkerConfig {
            regions: vec![
                MemoryRegion {
                    name: "FLASH".into(),
                    origin: 0x0800_0000,
                    size: 512 * 1024,
                    attrs: "rx".into(),
                },
                MemoryRegion {
                    name: "RAM".into(),
                    origin: 0x2000_0000,
                    size: 128 * 1024,
                    attrs: "rw".into(),
                },
            ],
            stack_size: 4096,
            entry: "_start".into(),
        }
    }

    #[test]
    fn generates_entry_point() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains("ENTRY(_start)"));
    }

    #[test]
    fn generates_memory_regions() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains("FLASH (rx)"));
        assert!(script.contains("RAM (rw)"));
        assert!(script.contains("ORIGIN = 0x08000000"));
        assert!(script.contains("ORIGIN = 0x20000000"));
    }

    #[test]
    fn generates_text_section() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains(".text :"));
        assert!(script.contains("*(.text .text.*)"));
        assert!(script.contains("> FLASH"));
    }

    #[test]
    fn generates_bss_section() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains(".bss :"));
        assert!(script.contains("__bss_start"));
        assert!(script.contains("__bss_end"));
    }

    #[test]
    fn generates_stack_section() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains(".stack (NOLOAD)"));
        assert!(script.contains("__stack_bottom"));
        assert!(script.contains("__stack_top"));
        assert!(script.contains("0x1000")); // 4096
    }

    #[test]
    fn generates_stack_pointer_symbol() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains("PROVIDE(__stack_ptr = __stack_top)"));
    }

    #[test]
    fn custom_stack_size() {
        let config = test_config().with_stack_size(16384);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("0x4000")); // 16384
    }

    #[test]
    fn custom_entry_point() {
        let config = test_config().with_entry("main");
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("ENTRY(main)"));
    }

    #[test]
    fn aarch64_default_config() {
        let target = TargetConfig::from_triple("aarch64-unknown-none").unwrap();
        let config = LinkerConfig::for_target(&target);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("FLASH"));
        assert!(script.contains("RAM"));
        assert!(script.contains("ENTRY(_start)"));
    }

    #[test]
    fn riscv64_default_config() {
        let target = TargetConfig::from_triple("riscv64gc-unknown-none-elf").unwrap();
        let config = LinkerConfig::for_target(&target);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("ORIGIN = 0x20000000")); // RISC-V FLASH
    }

    #[test]
    fn empty_regions_returns_error() {
        let config = LinkerConfig {
            regions: vec![],
            stack_size: 4096,
            entry: "_start".into(),
        };
        assert!(generate_linker_script(&config).is_err());
    }

    #[test]
    fn data_section_has_load_address() {
        let script = generate_linker_script(&test_config()).unwrap();
        // Data section should load from FLASH but live in RAM
        assert!(script.contains("> RAM AT > FLASH"));
    }

    #[test]
    fn x86_64_bare_metal_default_config() {
        let target = TargetConfig::from_triple("x86_64-unknown-none").unwrap();
        assert!(target.is_bare_metal);
        let config = LinkerConfig::for_target(&target);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("ENTRY(_start)"));
        assert!(script.contains("ORIGIN = 0x00100000")); // 1MB
        assert!(script.contains(".text :"));
        assert!(script.contains(".stack (NOLOAD)"));
    }

    #[test]
    fn for_target_generates_valid_script_all_archs() {
        for triple in &[
            "aarch64-unknown-none",
            "riscv64gc-unknown-none-elf",
            "x86_64-unknown-none",
        ] {
            let target = TargetConfig::from_triple(triple).unwrap();
            let config = LinkerConfig::for_target(&target);
            let script = generate_linker_script(&config).unwrap();
            assert!(
                script.contains("ENTRY(_start)"),
                "missing ENTRY for {triple}"
            );
            assert!(script.contains("MEMORY"), "missing MEMORY for {triple}");
            assert!(script.contains("SECTIONS"), "missing SECTIONS for {triple}");
            assert!(
                script.contains("__stack_ptr"),
                "missing stack symbol for {triple}"
            );
        }
    }

    #[test]
    fn interrupt_wrapper_contains_save_restore() {
        let wrapper = generate_interrupt_wrapper("irq_handler");
        assert!(wrapper.contains("__interrupt_irq_handler"));
        assert!(wrapper.contains("stp     x0,  x1,  [sp, #0]"));
        assert!(wrapper.contains("ldp     x0,  x1,  [sp, #0]"));
        assert!(wrapper.contains("bl      irq_handler"));
        assert!(wrapper.contains("eret"));
        assert!(wrapper.contains("SPSR_EL1"));
        assert!(wrapper.contains("ELR_EL1"));
    }

    #[test]
    fn interrupt_wrapper_saves_all_registers() {
        let wrapper = generate_interrupt_wrapper("timer_irq");
        // Verify all GP register pairs are saved
        for reg_pair in &[
            "x0,  x1", "x2,  x3", "x4,  x5", "x6,  x7", "x8,  x9", "x10, x11", "x12, x13",
            "x14, x15", "x16, x17", "x18, x19", "x20, x21", "x22, x23", "x24, x25", "x26, x27",
            "x28, x29",
        ] {
            assert!(
                wrapper.contains(&format!("stp     {reg_pair}")),
                "missing STP for {reg_pair}"
            );
            assert!(
                wrapper.contains(&format!("ldp     {reg_pair}")),
                "missing LDP for {reg_pair}"
            );
        }
        // x30 saved individually
        assert!(wrapper.contains("str     x30"));
        assert!(wrapper.contains("ldr     x30"));
    }

    // ═══════════════════════════════════════════════════════════════
    // x86_64 startup and linker script tests
    // ═══════════════════════════════════════════════════════════════

    #[test]
    fn x86_64_startup_has_multiboot2_header() {
        let startup = generate_x86_64_startup("kernel_main");
        assert!(startup.contains("0xE85250D6"), "missing Multiboot2 magic");
        assert!(
            startup.contains(".multiboot_header"),
            "missing multiboot_header section"
        );
    }

    #[test]
    fn x86_64_startup_has_start_symbol() {
        let startup = generate_x86_64_startup("kernel_main");
        assert!(startup.contains(".global _start"));
        assert!(startup.contains("_start:"));
    }

    #[test]
    fn x86_64_startup_sets_stack() {
        let startup = generate_x86_64_startup("kernel_main");
        assert!(startup.contains("rsp"), "must set stack pointer in 64-bit mode");
    }

    #[test]
    fn x86_64_startup_initializes_serial() {
        let startup = generate_x86_64_startup("kernel_main");
        // COM1 base = 0x3F8, IER = 0x3F9, LCR = 0x3FB, etc.
        assert!(startup.contains("0x3F8"), "missing COM1 base address");
        assert!(startup.contains("0x3FB"), "missing LCR register");
        assert!(
            startup.contains("out     dx, al"),
            "missing port I/O output"
        );
    }

    #[test]
    fn x86_64_startup_calls_entry_fn() {
        let startup = generate_x86_64_startup("my_kernel_entry");
        assert!(startup.contains("call    my_kernel_entry"));
    }

    #[test]
    fn x86_64_startup_halts_after_entry() {
        let startup = generate_x86_64_startup("kernel_main");
        assert!(startup.contains("cli"));
        assert!(startup.contains("hlt"));
    }

    #[test]
    fn x86_64_linker_script_has_multiboot_section() {
        let config = LinkerConfig::for_target(&TargetConfig {
            triple: target_lexicon::Triple::host(),
            arch: crate::codegen::target::Arch::X86_64,
            os: crate::codegen::target::Os::None,
            is_bare_metal: true,
            call_conv: cranelift_codegen::isa::CallConv::SystemV,
        });
        let script = generate_x86_64_linker_script(&config).unwrap();
        assert!(
            script.contains(".multiboot_header"),
            "missing multiboot_header section"
        );
        assert!(
            script.contains("KEEP(*(.multiboot_header))"),
            "multiboot_header must use KEEP"
        );
    }

    #[test]
    fn x86_64_linker_script_has_correct_layout() {
        let config = LinkerConfig::for_target(&TargetConfig {
            triple: target_lexicon::Triple::host(),
            arch: crate::codegen::target::Arch::X86_64,
            os: crate::codegen::target::Os::None,
            is_bare_metal: true,
            call_conv: cranelift_codegen::isa::CallConv::SystemV,
        });
        let script = generate_x86_64_linker_script(&config).unwrap();
        assert!(script.contains("ENTRY(_start)"));
        assert!(script.contains("0x00100000")); // FLASH origin at 1MB
        assert!(script.contains("__bss_start"));
        assert!(script.contains("__bss_end"));
        assert!(script.contains("__stack_top"));
    }

    #[test]
    fn x86_64_startup_is_64bit() {
        let startup = generate_x86_64_startup("kernel_main");
        assert!(startup.contains(".code64"), "must generate 64-bit code");
        assert!(startup.contains("rsp"), "must use 64-bit registers");
    }
}
