//! Linker script generation for bare-metal targets.
//!
//! Generates GNU ld-compatible linker scripts with proper ELF sections
//! for text, data, bss, and stack layout.

use super::target::{Arch, TargetConfig};
use super::CodegenError;

/// Memory region definition for linker scripts.
#[derive(Debug, Clone)]
pub struct MemoryRegion {
    /// Region name (e.g., "FLASH", "RAM").
    pub name: String,
    /// Base address.
    pub origin: u64,
    /// Size in bytes.
    pub size: u64,
    /// Attributes: r=read, w=write, x=execute.
    pub attrs: String,
}

/// Linker script configuration.
#[derive(Debug, Clone)]
pub struct LinkerConfig {
    /// Memory regions.
    pub regions: Vec<MemoryRegion>,
    /// Stack size in bytes.
    pub stack_size: u64,
    /// Entry point symbol.
    pub entry: String,
}

impl LinkerConfig {
    /// Creates a default linker config for the given target.
    pub fn for_target(target: &TargetConfig) -> Self {
        match target.arch {
            Arch::Aarch64 => Self {
                regions: vec![
                    MemoryRegion {
                        name: "FLASH".into(),
                        origin: 0x4000_0000,
                        size: 16 * 1024 * 1024, // 16MB kernel .text
                        attrs: "rx".into(),
                    },
                    MemoryRegion {
                        name: "RAM".into(),
                        origin: 0x4100_0000,
                        size: 128 * 1024 * 1024, // 128MB kernel data+heap+stack
                        attrs: "rwx".into(),
                    },
                ],
                stack_size: 64 * 1024, // 64KB kernel stack
                entry: "_start".into(),
            },
            Arch::Riscv64 => Self {
                regions: vec![
                    MemoryRegion {
                        name: "FLASH".into(),
                        origin: 0x2000_0000,
                        size: 16 * 1024 * 1024, // 16MB
                        attrs: "rx".into(),
                    },
                    MemoryRegion {
                        name: "RAM".into(),
                        origin: 0x8000_0000,
                        size: 64 * 1024 * 1024, // 64MB
                        attrs: "rwx".into(),
                    },
                ],
                stack_size: 8192,
                entry: "_start".into(),
            },
            Arch::X86_64 => Self {
                regions: vec![
                    MemoryRegion {
                        name: "FLASH".into(),
                        origin: 0x0010_0000, // 1MB
                        size: 16 * 1024 * 1024,
                        attrs: "rx".into(),
                    },
                    MemoryRegion {
                        name: "RAM".into(),
                        origin: 0x0200_0000,
                        size: 64 * 1024 * 1024,
                        attrs: "rwx".into(),
                    },
                ],
                stack_size: 16384,
                entry: "_start".into(),
            },
        }
    }

    /// Sets the stack size.
    pub fn with_stack_size(mut self, size: u64) -> Self {
        self.stack_size = size;
        self
    }

    /// Sets the entry point.
    pub fn with_entry(mut self, entry: &str) -> Self {
        self.entry = entry.to_string();
        self
    }
}

/// Generates a GNU ld-compatible linker script.
pub fn generate_linker_script(config: &LinkerConfig) -> Result<String, CodegenError> {
    if config.regions.is_empty() {
        return Err(CodegenError::AbiError(
            "linker config has no memory regions".into(),
        ));
    }

    let mut script = String::new();

    // Header
    script.push_str("/* Auto-generated by Fajar Lang compiler */\n\n");

    // Entry point
    script.push_str(&format!("ENTRY({})\n\n", config.entry));

    // Memory regions
    script.push_str("MEMORY\n{\n");
    for region in &config.regions {
        script.push_str(&format!(
            "    {} ({}) : ORIGIN = 0x{:08X}, LENGTH = 0x{:X}\n",
            region.name, region.attrs, region.origin, region.size
        ));
    }
    script.push_str("}\n\n");

    // Find FLASH and RAM regions
    let flash_name = config
        .regions
        .iter()
        .find(|r| r.attrs.contains('x'))
        .map(|r| r.name.as_str())
        .unwrap_or("FLASH");
    let ram_name = config
        .regions
        .iter()
        .find(|r| r.attrs.contains('w') && !r.attrs.contains('x'))
        .or_else(|| config.regions.iter().find(|r| r.attrs.contains('w')))
        .map(|r| r.name.as_str())
        .unwrap_or("RAM");

    // Sections
    script.push_str("SECTIONS\n{\n");

    // .text (code)
    script.push_str(&format!(
        "    .text :\n    {{\n        *(.text.start)\n        *(.text .text.*)\n    }} > {flash_name}\n\n"
    ));

    // .rodata (read-only data)
    script.push_str(&format!(
        "    .rodata :\n    {{\n        *(.rodata .rodata.*)\n    }} > {flash_name}\n\n"
    ));

    // .data (initialized data)
    script.push_str(&format!(
        "    .data :\n    {{\n        __data_start = .;\n        *(.data .data.*)\n        __data_end = .;\n    }} > {ram_name} AT > {flash_name}\n\n"
    ));

    // .bss (zero-initialized data)
    script.push_str(&format!(
        "    .bss :\n    {{\n        __bss_start = .;\n        *(.bss .bss.*)\n        *(COMMON)\n        __bss_end = .;\n    }} > {ram_name}\n\n"
    ));

    // Stack
    script.push_str(&format!(
        "    .stack (NOLOAD) :\n    {{\n        . = ALIGN(16);\n        __stack_bottom = .;\n        . += 0x{:X};\n        __stack_top = .;\n    }} > {ram_name}\n\n",
        config.stack_size
    ));

    // Provide symbols
    script.push_str("    /DISCARD/ :\n    {\n        *(.comment)\n        *(.note*)\n    }\n");

    script.push_str("}\n\n");

    // Stack pointer symbol
    script.push_str("PROVIDE(__stack_ptr = __stack_top);\n");

    Ok(script)
}

/// Generates aarch64 bare-metal startup assembly.
///
/// This stub:
/// 1. Sets the stack pointer from linker symbol `__stack_top`
/// 2. Zeros the BSS section (`__bss_start` to `__bss_end`)
/// 3. Calls the user's entry function (default: `kernel_main`)
/// 4. On return, enters WFE halt loop
pub fn generate_aarch64_startup(entry_fn: &str) -> String {
    format!(
        r#"/* Auto-generated aarch64 bare-metal startup — FajarOS */
.section .text.start, "ax"
.global _start
.type _start, @function

_start:
    /* Set stack pointer */
    ldr     x0, =__stack_top
    mov     sp, x0

    /* Zero BSS section */
    ldr     x0, =__bss_start
    ldr     x1, =__bss_end
.Lbss_loop:
    cmp     x0, x1
    b.ge    .Lbss_done
    str     xzr, [x0], #8
    b       .Lbss_loop
.Lbss_done:

    /* Set VBAR_EL1 to exception vector table */
    ldr     x0, =__vectors
    msr     VBAR_EL1, x0
    isb

    /* Call kernel entry */
    bl      {entry_fn}

    /* Halt loop (should never return) */
.Lhalt:
    wfe
    b       .Lhalt

.size _start, . - _start

/* ═══════════════════════════════════════════════════════════════════
   Exception Vector Table (aarch64 EL1)
   16 entries × 128 bytes each = 2048 bytes, 2KB aligned
   Layout:
     Current EL, SP_EL0:    Sync, IRQ, FIQ, SError
     Current EL, SP_ELx:    Sync, IRQ, FIQ, SError
     Lower EL, AArch64:     Sync, IRQ, FIQ, SError
     Lower EL, AArch32:     Sync, IRQ, FIQ, SError
   ═══════════════════════════════════════════════════════════════════ */

.balign 2048
.global __vectors
__vectors:
    /* Current EL, SP_EL0 — Sync */
    b       __exc_sync_cur
    .balign 128
    /* Current EL, SP_EL0 — IRQ */
    b       __exc_irq_cur
    .balign 128
    /* Current EL, SP_EL0 — FIQ */
    b       __exc_fiq
    .balign 128
    /* Current EL, SP_EL0 — SError */
    b       __exc_serror
    .balign 128

    /* Current EL, SP_ELx — Sync */
    b       __exc_sync_cur
    .balign 128
    /* Current EL, SP_ELx — IRQ */
    b       __exc_irq_cur
    .balign 128
    /* Current EL, SP_ELx — FIQ */
    b       __exc_fiq
    .balign 128
    /* Current EL, SP_ELx — SError */
    b       __exc_serror
    .balign 128

    /* Lower EL, AArch64 — Sync (syscalls come here) */
    b       __exc_sync_lower
    .balign 128
    /* Lower EL, AArch64 — IRQ */
    b       __exc_irq_lower
    .balign 128
    /* Lower EL, AArch64 — FIQ */
    b       __exc_fiq
    .balign 128
    /* Lower EL, AArch64 — SError */
    b       __exc_serror
    .balign 128

    /* Lower EL, AArch32 — Sync */
    b       __exc_sync_lower
    .balign 128
    /* Lower EL, AArch32 — IRQ */
    b       __exc_irq_lower
    .balign 128
    /* Lower EL, AArch32 — FIQ */
    b       __exc_fiq
    .balign 128
    /* Lower EL, AArch32 — SError */
    b       __exc_serror
    .balign 128

/* ─── Exception stubs: save context, call handler, restore ─── */

/* Macro: save all GP registers to stack (256 bytes) */
.macro SAVE_CONTEXT
    sub     sp, sp, #256
    stp     x0, x1, [sp, #0]
    stp     x2, x3, [sp, #16]
    stp     x4, x5, [sp, #32]
    stp     x6, x7, [sp, #48]
    stp     x8, x9, [sp, #64]
    stp     x10, x11, [sp, #80]
    stp     x12, x13, [sp, #96]
    stp     x14, x15, [sp, #112]
    stp     x16, x17, [sp, #128]
    stp     x18, x19, [sp, #144]
    stp     x20, x21, [sp, #160]
    stp     x22, x23, [sp, #176]
    stp     x24, x25, [sp, #192]
    stp     x26, x27, [sp, #208]
    stp     x28, x29, [sp, #224]
    mrs     x0, ELR_EL1
    mrs     x1, SPSR_EL1
    stp     x30, x0, [sp, #240]
.endm

.macro RESTORE_CONTEXT
    ldp     x30, x0, [sp, #240]
    msr     ELR_EL1, x0
    ldp     x0, x1, [sp, #0]
    ldp     x2, x3, [sp, #16]
    ldp     x4, x5, [sp, #32]
    ldp     x6, x7, [sp, #48]
    ldp     x8, x9, [sp, #64]
    ldp     x10, x11, [sp, #80]
    ldp     x12, x13, [sp, #96]
    ldp     x14, x15, [sp, #112]
    ldp     x16, x17, [sp, #128]
    ldp     x18, x19, [sp, #144]
    ldp     x20, x21, [sp, #160]
    ldp     x22, x23, [sp, #176]
    ldp     x24, x25, [sp, #192]
    ldp     x26, x27, [sp, #208]
    ldp     x28, x29, [sp, #224]
    add     sp, sp, #256
.endm

/* Sync exception from current EL */
.global __exc_sync_cur
__exc_sync_cur:
    SAVE_CONTEXT
    mrs     x0, ESR_EL1     /* x0 = ESR (exception syndrome) */
    mrs     x1, ELR_EL1     /* x1 = ELR (return address) */
    mrs     x2, FAR_EL1     /* x2 = FAR (fault address) */
    bl      fj_exception_sync
    RESTORE_CONTEXT
    eret

/* IRQ from current EL */
.global __exc_irq_cur
__exc_irq_cur:
    SAVE_CONTEXT
    bl      fj_exception_irq
    RESTORE_CONTEXT
    eret

/* Sync exception from lower EL (syscalls) */
.global __exc_sync_lower
__exc_sync_lower:
    SAVE_CONTEXT
    mrs     x0, ESR_EL1
    mrs     x1, ELR_EL1
    mrs     x2, FAR_EL1
    bl      fj_exception_sync
    RESTORE_CONTEXT
    eret

/* IRQ from lower EL */
.global __exc_irq_lower
__exc_irq_lower:
    SAVE_CONTEXT
    bl      fj_exception_irq
    RESTORE_CONTEXT
    eret

/* FIQ (unused, halt) */
.global __exc_fiq
__exc_fiq:
    b       __exc_fiq

/* SError (halt) */
.global __exc_serror
__exc_serror:
    b       __exc_serror

/* Bare-metal runtime: volatile I/O */
.global fj_rt_volatile_write
.type fj_rt_volatile_write, @function
fj_rt_volatile_write:
    /* x0 = addr, x1 = value */
    str     x1, [x0]
    ret
.size fj_rt_volatile_write, . - fj_rt_volatile_write

.global fj_rt_volatile_read
.type fj_rt_volatile_read, @function
fj_rt_volatile_read:
    /* x0 = addr, returns value in x0 */
    ldr     x0, [x0]
    ret
.size fj_rt_volatile_read, . - fj_rt_volatile_read

.global fj_rt_volatile_write_u8
.type fj_rt_volatile_write_u8, @function
fj_rt_volatile_write_u8:
    strb    w1, [x0]
    ret
.size fj_rt_volatile_write_u8, . - fj_rt_volatile_write_u8

.global fj_rt_volatile_read_u8
.type fj_rt_volatile_read_u8, @function
fj_rt_volatile_read_u8:
    ldrb    w0, [x0]
    ret
.size fj_rt_volatile_read_u8, . - fj_rt_volatile_read_u8

.global fj_rt_volatile_write_u16
.type fj_rt_volatile_write_u16, @function
fj_rt_volatile_write_u16:
    strh    w1, [x0]
    ret
.size fj_rt_volatile_write_u16, . - fj_rt_volatile_write_u16

.global fj_rt_volatile_read_u16
.type fj_rt_volatile_read_u16, @function
fj_rt_volatile_read_u16:
    ldrh    w0, [x0]
    ret
.size fj_rt_volatile_read_u16, . - fj_rt_volatile_read_u16

.global fj_rt_volatile_write_u32
.type fj_rt_volatile_write_u32, @function
fj_rt_volatile_write_u32:
    str     w1, [x0]
    ret
.size fj_rt_volatile_write_u32, . - fj_rt_volatile_write_u32

.global fj_rt_volatile_read_u32
.type fj_rt_volatile_read_u32, @function
fj_rt_volatile_read_u32:
    ldr     w0, [x0]
    ret
.size fj_rt_volatile_read_u32, . - fj_rt_volatile_read_u32

/* Bare-metal runtime: memcpy/memset/halt */
.global fj_rt_bare_memcpy
.type fj_rt_bare_memcpy, @function
fj_rt_bare_memcpy:
    /* x0=dst, x1=src, x2=n */
    mov     x3, x0
.Lmcpy:
    cbz     x2, .Lmcpy_done
    ldrb    w4, [x1], #1
    strb    w4, [x0], #1
    sub     x2, x2, #1
    b       .Lmcpy
.Lmcpy_done:
    mov     x0, x3
    ret
.size fj_rt_bare_memcpy, . - fj_rt_bare_memcpy

.global fj_rt_bare_memset
.type fj_rt_bare_memset, @function
fj_rt_bare_memset:
    /* x0=dst, x1=val, x2=n */
    mov     x3, x0
.Lmset:
    cbz     x2, .Lmset_done
    strb    w1, [x0], #1
    sub     x2, x2, #1
    b       .Lmset
.Lmset_done:
    mov     x0, x3
    ret
.size fj_rt_bare_memset, . - fj_rt_bare_memset

.global fj_rt_bare_halt
.type fj_rt_bare_halt, @function
fj_rt_bare_halt:
    wfe
    b       fj_rt_bare_halt
.size fj_rt_bare_halt, . - fj_rt_bare_halt

.global fj_rt_bare_print_i64
.type fj_rt_bare_print_i64, @function
fj_rt_bare_print_i64:
    /* Minimal: just write value as single char to UART */
    ldr     x1, =0x09000000
    add     w2, w0, #48   /* convert digit to ASCII (works for 0-9) */
    strb    w2, [x1]
    mov     w2, #10       /* newline */
    strb    w2, [x1]
    ret
.size fj_rt_bare_print_i64, . - fj_rt_bare_print_i64

.global fj_rt_bare_print
.type fj_rt_bare_print, @function
fj_rt_bare_print:
    /* x0=ptr, x1=len */
    ldr     x2, =0x09000000
.Lprint:
    cbz     x1, .Lprint_done
    ldrb    w3, [x0], #1
    strb    w3, [x2]
    sub     x1, x1, #1
    b       .Lprint
.Lprint_done:
    ret
.size fj_rt_bare_print, . - fj_rt_bare_print
"#
    )
}

// ═══════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> LinkerConfig {
        LinkerConfig {
            regions: vec![
                MemoryRegion {
                    name: "FLASH".into(),
                    origin: 0x0800_0000,
                    size: 512 * 1024,
                    attrs: "rx".into(),
                },
                MemoryRegion {
                    name: "RAM".into(),
                    origin: 0x2000_0000,
                    size: 128 * 1024,
                    attrs: "rw".into(),
                },
            ],
            stack_size: 4096,
            entry: "_start".into(),
        }
    }

    #[test]
    fn generates_entry_point() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains("ENTRY(_start)"));
    }

    #[test]
    fn generates_memory_regions() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains("FLASH (rx)"));
        assert!(script.contains("RAM (rw)"));
        assert!(script.contains("ORIGIN = 0x08000000"));
        assert!(script.contains("ORIGIN = 0x20000000"));
    }

    #[test]
    fn generates_text_section() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains(".text :"));
        assert!(script.contains("*(.text .text.*)"));
        assert!(script.contains("> FLASH"));
    }

    #[test]
    fn generates_bss_section() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains(".bss :"));
        assert!(script.contains("__bss_start"));
        assert!(script.contains("__bss_end"));
    }

    #[test]
    fn generates_stack_section() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains(".stack (NOLOAD)"));
        assert!(script.contains("__stack_bottom"));
        assert!(script.contains("__stack_top"));
        assert!(script.contains("0x1000")); // 4096
    }

    #[test]
    fn generates_stack_pointer_symbol() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains("PROVIDE(__stack_ptr = __stack_top)"));
    }

    #[test]
    fn custom_stack_size() {
        let config = test_config().with_stack_size(16384);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("0x4000")); // 16384
    }

    #[test]
    fn custom_entry_point() {
        let config = test_config().with_entry("main");
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("ENTRY(main)"));
    }

    #[test]
    fn aarch64_default_config() {
        let target = TargetConfig::from_triple("aarch64-unknown-none").unwrap();
        let config = LinkerConfig::for_target(&target);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("FLASH"));
        assert!(script.contains("RAM"));
        assert!(script.contains("ENTRY(_start)"));
    }

    #[test]
    fn riscv64_default_config() {
        let target = TargetConfig::from_triple("riscv64gc-unknown-none-elf").unwrap();
        let config = LinkerConfig::for_target(&target);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("ORIGIN = 0x20000000")); // RISC-V FLASH
    }

    #[test]
    fn empty_regions_returns_error() {
        let config = LinkerConfig {
            regions: vec![],
            stack_size: 4096,
            entry: "_start".into(),
        };
        assert!(generate_linker_script(&config).is_err());
    }

    #[test]
    fn data_section_has_load_address() {
        let script = generate_linker_script(&test_config()).unwrap();
        // Data section should load from FLASH but live in RAM
        assert!(script.contains("> RAM AT > FLASH"));
    }

    #[test]
    fn x86_64_bare_metal_default_config() {
        let target = TargetConfig::from_triple("x86_64-unknown-none").unwrap();
        assert!(target.is_bare_metal);
        let config = LinkerConfig::for_target(&target);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("ENTRY(_start)"));
        assert!(script.contains("ORIGIN = 0x00100000")); // 1MB
        assert!(script.contains(".text :"));
        assert!(script.contains(".stack (NOLOAD)"));
    }

    #[test]
    fn for_target_generates_valid_script_all_archs() {
        for triple in &[
            "aarch64-unknown-none",
            "riscv64gc-unknown-none-elf",
            "x86_64-unknown-none",
        ] {
            let target = TargetConfig::from_triple(triple).unwrap();
            let config = LinkerConfig::for_target(&target);
            let script = generate_linker_script(&config).unwrap();
            assert!(
                script.contains("ENTRY(_start)"),
                "missing ENTRY for {triple}"
            );
            assert!(script.contains("MEMORY"), "missing MEMORY for {triple}");
            assert!(script.contains("SECTIONS"), "missing SECTIONS for {triple}");
            assert!(
                script.contains("__stack_ptr"),
                "missing stack symbol for {triple}"
            );
        }
    }
}
