//! Linker script generation for bare-metal targets.
//!
//! Generates GNU ld-compatible linker scripts with proper ELF sections
//! for text, data, bss, and stack layout.

use super::target::{Arch, TargetConfig};
use super::CodegenError;

/// Memory region definition for linker scripts.
#[derive(Debug, Clone)]
pub struct MemoryRegion {
    /// Region name (e.g., "FLASH", "RAM").
    pub name: String,
    /// Base address.
    pub origin: u64,
    /// Size in bytes.
    pub size: u64,
    /// Attributes: r=read, w=write, x=execute.
    pub attrs: String,
}

/// Linker script configuration.
#[derive(Debug, Clone)]
pub struct LinkerConfig {
    /// Memory regions.
    pub regions: Vec<MemoryRegion>,
    /// Stack size in bytes.
    pub stack_size: u64,
    /// Entry point symbol.
    pub entry: String,
}

impl LinkerConfig {
    /// Creates a default linker config for the given target.
    pub fn for_target(target: &TargetConfig) -> Self {
        match target.arch {
            Arch::Aarch64 => Self {
                regions: vec![
                    MemoryRegion {
                        name: "FLASH".into(),
                        origin: 0x4000_0000,
                        size: 64 * 1024 * 1024, // 64MB
                        attrs: "rx".into(),
                    },
                    MemoryRegion {
                        name: "RAM".into(),
                        origin: 0x8000_0000,
                        size: 128 * 1024 * 1024, // 128MB
                        attrs: "rwx".into(),
                    },
                ],
                stack_size: 8192,
                entry: "_start".into(),
            },
            Arch::Riscv64 => Self {
                regions: vec![
                    MemoryRegion {
                        name: "FLASH".into(),
                        origin: 0x2000_0000,
                        size: 16 * 1024 * 1024, // 16MB
                        attrs: "rx".into(),
                    },
                    MemoryRegion {
                        name: "RAM".into(),
                        origin: 0x8000_0000,
                        size: 64 * 1024 * 1024, // 64MB
                        attrs: "rwx".into(),
                    },
                ],
                stack_size: 8192,
                entry: "_start".into(),
            },
            Arch::X86_64 => Self {
                regions: vec![
                    MemoryRegion {
                        name: "FLASH".into(),
                        origin: 0x0010_0000, // 1MB
                        size: 16 * 1024 * 1024,
                        attrs: "rx".into(),
                    },
                    MemoryRegion {
                        name: "RAM".into(),
                        origin: 0x0200_0000,
                        size: 64 * 1024 * 1024,
                        attrs: "rwx".into(),
                    },
                ],
                stack_size: 16384,
                entry: "_start".into(),
            },
        }
    }

    /// Sets the stack size.
    pub fn with_stack_size(mut self, size: u64) -> Self {
        self.stack_size = size;
        self
    }

    /// Sets the entry point.
    pub fn with_entry(mut self, entry: &str) -> Self {
        self.entry = entry.to_string();
        self
    }
}

/// Generates a GNU ld-compatible linker script.
pub fn generate_linker_script(config: &LinkerConfig) -> Result<String, CodegenError> {
    if config.regions.is_empty() {
        return Err(CodegenError::AbiError(
            "linker config has no memory regions".into(),
        ));
    }

    let mut script = String::new();

    // Header
    script.push_str("/* Auto-generated by Fajar Lang compiler */\n\n");

    // Entry point
    script.push_str(&format!("ENTRY({})\n\n", config.entry));

    // Memory regions
    script.push_str("MEMORY\n{\n");
    for region in &config.regions {
        script.push_str(&format!(
            "    {} ({}) : ORIGIN = 0x{:08X}, LENGTH = 0x{:X}\n",
            region.name, region.attrs, region.origin, region.size
        ));
    }
    script.push_str("}\n\n");

    // Find FLASH and RAM regions
    let flash_name = config
        .regions
        .iter()
        .find(|r| r.attrs.contains('x'))
        .map(|r| r.name.as_str())
        .unwrap_or("FLASH");
    let ram_name = config
        .regions
        .iter()
        .find(|r| r.attrs.contains('w') && !r.attrs.contains('x'))
        .or_else(|| config.regions.iter().find(|r| r.attrs.contains('w')))
        .map(|r| r.name.as_str())
        .unwrap_or("RAM");

    // Sections
    script.push_str("SECTIONS\n{\n");

    // .text (code)
    script.push_str(&format!(
        "    .text :\n    {{\n        *(.text.start)\n        *(.text .text.*)\n    }} > {flash_name}\n\n"
    ));

    // .rodata (read-only data)
    script.push_str(&format!(
        "    .rodata :\n    {{\n        *(.rodata .rodata.*)\n    }} > {flash_name}\n\n"
    ));

    // .data (initialized data)
    script.push_str(&format!(
        "    .data :\n    {{\n        __data_start = .;\n        *(.data .data.*)\n        __data_end = .;\n    }} > {ram_name} AT > {flash_name}\n\n"
    ));

    // .bss (zero-initialized data)
    script.push_str(&format!(
        "    .bss :\n    {{\n        __bss_start = .;\n        *(.bss .bss.*)\n        *(COMMON)\n        __bss_end = .;\n    }} > {ram_name}\n\n"
    ));

    // Stack
    script.push_str(&format!(
        "    .stack (NOLOAD) :\n    {{\n        . = ALIGN(16);\n        __stack_bottom = .;\n        . += 0x{:X};\n        __stack_top = .;\n    }} > {ram_name}\n\n",
        config.stack_size
    ));

    // Provide symbols
    script.push_str("    /DISCARD/ :\n    {\n        *(.comment)\n        *(.note*)\n    }\n");

    script.push_str("}\n\n");

    // Stack pointer symbol
    script.push_str("PROVIDE(__stack_ptr = __stack_top);\n");

    Ok(script)
}

// ═══════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> LinkerConfig {
        LinkerConfig {
            regions: vec![
                MemoryRegion {
                    name: "FLASH".into(),
                    origin: 0x0800_0000,
                    size: 512 * 1024,
                    attrs: "rx".into(),
                },
                MemoryRegion {
                    name: "RAM".into(),
                    origin: 0x2000_0000,
                    size: 128 * 1024,
                    attrs: "rw".into(),
                },
            ],
            stack_size: 4096,
            entry: "_start".into(),
        }
    }

    #[test]
    fn generates_entry_point() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains("ENTRY(_start)"));
    }

    #[test]
    fn generates_memory_regions() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains("FLASH (rx)"));
        assert!(script.contains("RAM (rw)"));
        assert!(script.contains("ORIGIN = 0x08000000"));
        assert!(script.contains("ORIGIN = 0x20000000"));
    }

    #[test]
    fn generates_text_section() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains(".text :"));
        assert!(script.contains("*(.text .text.*)"));
        assert!(script.contains("> FLASH"));
    }

    #[test]
    fn generates_bss_section() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains(".bss :"));
        assert!(script.contains("__bss_start"));
        assert!(script.contains("__bss_end"));
    }

    #[test]
    fn generates_stack_section() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains(".stack (NOLOAD)"));
        assert!(script.contains("__stack_bottom"));
        assert!(script.contains("__stack_top"));
        assert!(script.contains("0x1000")); // 4096
    }

    #[test]
    fn generates_stack_pointer_symbol() {
        let script = generate_linker_script(&test_config()).unwrap();
        assert!(script.contains("PROVIDE(__stack_ptr = __stack_top)"));
    }

    #[test]
    fn custom_stack_size() {
        let config = test_config().with_stack_size(16384);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("0x4000")); // 16384
    }

    #[test]
    fn custom_entry_point() {
        let config = test_config().with_entry("main");
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("ENTRY(main)"));
    }

    #[test]
    fn aarch64_default_config() {
        let target = TargetConfig::from_triple("aarch64-unknown-none").unwrap();
        let config = LinkerConfig::for_target(&target);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("FLASH"));
        assert!(script.contains("RAM"));
        assert!(script.contains("ENTRY(_start)"));
    }

    #[test]
    fn riscv64_default_config() {
        let target = TargetConfig::from_triple("riscv64gc-unknown-none-elf").unwrap();
        let config = LinkerConfig::for_target(&target);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("ORIGIN = 0x20000000")); // RISC-V FLASH
    }

    #[test]
    fn empty_regions_returns_error() {
        let config = LinkerConfig {
            regions: vec![],
            stack_size: 4096,
            entry: "_start".into(),
        };
        assert!(generate_linker_script(&config).is_err());
    }

    #[test]
    fn data_section_has_load_address() {
        let script = generate_linker_script(&test_config()).unwrap();
        // Data section should load from FLASH but live in RAM
        assert!(script.contains("> RAM AT > FLASH"));
    }

    #[test]
    fn x86_64_bare_metal_default_config() {
        let target = TargetConfig::from_triple("x86_64-unknown-none").unwrap();
        assert!(target.is_bare_metal);
        let config = LinkerConfig::for_target(&target);
        let script = generate_linker_script(&config).unwrap();
        assert!(script.contains("ENTRY(_start)"));
        assert!(script.contains("ORIGIN = 0x00100000")); // 1MB
        assert!(script.contains(".text :"));
        assert!(script.contains(".stack (NOLOAD)"));
    }

    #[test]
    fn for_target_generates_valid_script_all_archs() {
        for triple in &[
            "aarch64-unknown-none",
            "riscv64gc-unknown-none-elf",
            "x86_64-unknown-none",
        ] {
            let target = TargetConfig::from_triple(triple).unwrap();
            let config = LinkerConfig::for_target(&target);
            let script = generate_linker_script(&config).unwrap();
            assert!(
                script.contains("ENTRY(_start)"),
                "missing ENTRY for {triple}"
            );
            assert!(script.contains("MEMORY"), "missing MEMORY for {triple}");
            assert!(script.contains("SECTIONS"), "missing SECTIONS for {triple}");
            assert!(
                script.contains("__stack_ptr"),
                "missing stack symbol for {triple}"
            );
        }
    }
}
